### ISSUE TITLE
Missing tool descriptions

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#101]
There are several tools without any description in them. Some of them look pretty rudimentary, so new users (including myself as I do not use these tools) have absolutely no idea what they do. Can someone give me some descriptions of tools that we could display to the user?

To find them, just mouse over all the tools until you find an empty description. Such as PSA Viewer.

**Comment by Kinkojiro** [comment]
**Property Database** - scans ME3 and creates a database of all the classes and properties for those classes that Bioware uses.

**Property Dumper** - DEPRECATED - use Package Dumper

**Property Manager** - DEPRECATED - allows the player to create a database by hand of classes and properties.

**PSA Viewer**  - View the data contained in a PSA animation file extracted using Gildor's umodel toolkit.

**PSK Viewer** - View the data contained in a PSK skeletal mesh file extracted using Gildor's umodel toolkit.

**Comment by Mgamerz** [comment]
All but Animation Explorer has a description now.

**Comment by Kinkojiro** [comment]
Animation Explorer can build a database of all the files containing animtrees and complete animsets in ME3.  You can import and export Animsets to PSA files.
