### ISSUE TITLE
Bug: Corruption when Trashing Exports

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#106]
Trashing an export and it's children using any version of the Fork, will cause a critical error in the package after saving and reopening the file. Attempting to load the package in classic Package Editor will result in a failure to load that looks like this:

![mg_I_swear_to_god](https://user-images.githubusercontent.com/39216095/55441654-d6060c80-55ab-11e9-9794-d7ace9d5f950.png)

The file will open in PackEd WPF, but clicking on any children under the Trash export will result in this error, and a subsequent toolset crash.

![eyerolling_intensifies](https://user-images.githubusercontent.com/39216095/55441688-f635cb80-55ab-11e9-8c05-2cda0c68f405.png)

A CTD will occur when the game attempts to load the package.

To reproduce:
1. Download this package: 
[BioD_End001_200AAGun.zip](https://github.com/Mgamerz/ME3Explorer/files/3036204/BioD_End001_200AAGun.zip)

2. Trash an export and it's kids. Children that I need trashed include wwise banks and objects. Trash either Wwise_DLC_Mapmod_Music_Strm_Lp, Wwise_DLC_Mapmod_NonLpStm, or Wwise_BCM_streaming.
3. Save
4. Open Package again.

Version:
This was first encountered in .14. Occurs in the new 4.0 as well.

**Comment by Mgamerz** [comment]
Awaiting validation of fix from e0069e9a0d378f09999e6e6a8c18c41b89cf43cf

**Comment by ghost** [comment]
New commit fixes the issue. No package errors or game crashes. Tested in-game and can confirm.

**Comment by Mgamerz** [comment]
Good to hear.
