### ISSUE TITLE
New Icons for 4.0

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#107]
![preview](https://user-images.githubusercontent.com/2738836/55450304-de4e4f80-558b-11e9-9522-9ce5ab4818c6.png)

Since we don't have a consistent tool icon set, we are re-creating all icons for tools. They keep the same visual format but will remain consistent. The new icons are higher resolution which will be rendered at higher quality when display scaling is higher than 100% (so high dpi displays).

Download the below icon template to create an icon. Inside of the zip is an XCF file which is opened in GIMP.
[IconTemplate.zip](https://github.com/Mgamerz/ME3Explorer/files/3036689/IconTemplate.zip)

Directions on how to make an icon:

1. Delete the contents of Stroke layer. This is the layer that shadows the top text
2. Change the top layer to a 3 or 4 letter word or acronym that matches the tool. If it's an existing tool, you should most times use the same text.
3. Right click the top layer, and select _alpha to selection_.
4. Go to the Select menu and choose Grow. Grow by 4 pixels.
5. Set the Stroke layer as the active layer, and using the fill tool, fill the selected area with black.
6. Press CTRL+SHIFT+A to unselect everything.
7. Change the text in the bottom lines. Turn off the second line and second backdrop if only using one line. When changing this line don't delete the first character, gimp is dumb and loses all of the font settings if you do. Only after you type in the real first letter can you erase the original first letter.
8. Set the layer "Pasted Layer" as the active layer. This is the background layer.
9. Open the Colors menu and choose Colorize.
10. Change color to something that looks like old icon, or whatever you want for a new one.
11. Go to File menu and do Save as... save the xcf file somewhere. It is important to do this in this order.
12. Right click any layer and select Flatten Image (at the bottom)
13. Go to File menu again and this time select Export Image. Export the image with the following filename format: toolname_256x256.ico
14. Use the default settings. Upload the ico and xcf for submission to the toolset. We want the xcf so we don't have to recreate colors.

Guidelines:
 - Do no change any font sizes.
 - Items are already aligned. Don't change them
 - The black bar is for the full title of the application. Even if the top text is part of the name, type the whole application. For example, "Hex Converter" should have the top text of HEX and the bottom text of HEX CONVERTER, not just CONVERTER.

The following icons are still needed:

- ~~FaceFXAnimSet Editor~~
- ~~WwiseBank Editor~~
- ~~SFAR Editor 2~~
- ~~UDK Explorer~~
- ~~Image Engine~~
- ~~Mesh Database (not Meshplorer 2)~~
- ~~Plot Database~~
- ~~Property Database~~
- ~~Script Database~~
- ~~Animation Explorer~~
- ~~Interp Viewer~~
- ~~PSA Viewer~~
- ~~PSK Viewer~~
- ~~Subtitle Scanner~~
- ~~Bik Movie Extractor~~
- ~~Coalesced Editor (is this actually an editor or a compiler/decompiler)~~
- ~~ME3 + ME2 TLK Editor (is this actually an editor or a compiler/decompiler)~~
- ~~ModMaker~~
- ~~TPF Tools~~
- ~~Property Dumper~~ << Tool Removed
- ~~Property Manager~~ << Tool Removed

**Comment by Kinkojiro** [comment]
Let me know if there are any outstanding.  I believe you should have them all perhaps with the exception of TPF Tools.

**Comment by Mgamerz** [comment]
Updated - need ModMaker, as well as the coalesced and tlk compilers. I don't think the "Editor" name is accurate since there is no editor functionality in these tools. @SirCxyrtyx thoughts? Should these be renamed to Compiler/Decompiler instead of Editor?

**Comment by SirCxyrtyx** [comment]
Editor clearly conveys the use case of the tool. Might not be obvious for a user looking to edit a tlk that they should open the TLK Compiler tool. It's perhaps a small fib, but not really a harmful one.

**Comment by Mgamerz** [comment]
All icons have been ported over, so the icon set (for now) is complete.
