### ISSUE TITLE
Usable properties don't show up in AddProperty screen

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#109]
Object properties named _EvolvedPowerClass1_ and _EvolvedPowerClass2_ (ME2) are working on any SFXPower_<PowerName> (they show properly in interpreter when added, and they are working in-game), but they aren't listed in any of AddProperty screens, so they have to be added by hex editing.
Example files, before and after adding these properties to an export. Export 137.
[rhgdthr.zip](https://github.com/Mgamerz/ME3Explorer/files/3048543/rhgdthr.zip)

**Comment by SirCxyrtyx** [comment]
Fixed. All properties should be in the AddProperty dialog now. Thanks!
