### ISSUE TITLE
Suggestion: Refresh TLKs menu option

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#11]
In package editor (mainly, but also sequence editor and dialogue editor) it would be useful to have a menu option to force ME3Exp to refresh the tlks, rather than having to exit the program entirely when you update the tlks in order to force the correct strings to be shown.

When doing large conversations this makes life a lot easier.

**Comment by Mgamerz** [comment]
Implemented in #13
