### ISSUE TITLE
PackageEd: Crash on cloning of import class (BETA)

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#110]
**Describe the bug**
When cloning an import in interpreter and then closing, an exception is thrown.

**To Reproduce**
Open file.
Clone import class.
Exit.

In VS the exception is in InterpreterWPF line 1751

![image](https://user-images.githubusercontent.com/15979398/56125563-1cc31180-5f71-11e9-819b-415cd1a7e68d.png)

**Comment by Mgamerz** [comment]
I will fix this soon, it has to do with not handling the result of the "do you want to close this with unsaved changes?" dialog. This also will happen on Pathfinding Editor WPF in my branch until I fix it.

**Comment by Mgamerz** [comment]
This bug was fixed in 0eb24992f947b8950a21517a8b011d40979ea365
