### ISSUE TITLE
Relinking w/ drag and drop messes up on InterpGroups with "Play FOVO" objects

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#115]
**Describe the bug**
When cloning InterpGroups containing Play FOVO exports, it seems to cause irreversible corruption on the .pcc that makes it unable to restore the original conversation sound and related FaceFX, either on the Play FOVO clone or the original respective VOElement it was copied to.

**To Reproduce**
1. Open "BioD_CitHub_001ProCit_LOC_INT.pcc" in either Sequence Editor or Package Editor
2o. If you opened in Seq. Editor first, find the Interp that reads "The Admiral is right..." and open that in package editor.
2. In package editor take the interpGroup that contains the export "SFXInterpTrackPlayFaceOnlyVO", then drag and drop this entire InterpGroup to another InterpData which does not contain such an element, but contains 'Conversation' or 'Player' Exports. You will get a notification that the relink failed partially.
3. If you play the game, once it gets to the InterpData you cloned to, the character with the VOElement will no longer speak, nor will you be able to use the Play FOVO.

**Version information:**
Previous and current build of ME3Explorer.

**Comment by ghost** [comment]
This doesn't sound like a toolset error.
1) Did you check the FindActor tag on the FOVO?
2) Did you add the new InterpGroup to the Interpdata's list?
3) What exactly wasn't re-linked correctly? The toolset always specifies it.
4) If you're cloning this within the same package, I strongly recommend that you clone the group within the original InterpData, and then move it manually by editing Meta Data. It's safer, and it will automatically re-index all new exports.

**Comment by Mgamerz** [comment]
Please define "current" build. What is the signing date. Current is very different from dev to end user.

**Comment by linkenski** [comment]
I was doing it using old packageEd in .14

**Comment by Mgamerz** [comment]
Package Editor Classic has been deprecated. The relinker in that version has not received the same fixes and improvements that the WPF version uses which is significantly better.

Package Editor Classic will be removed once we ship 4.0.

**Comment by linkenski** [comment]
I have not run into the same issue since then, and I think back then, it must've been a common relinking error where it looks for an export number according to the file it came from which has a foreign number in the target file. You may close the topic.
