### ISSUE TITLE
Minor issues: Beta 4.0

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#116]
These are minor issues I have noticed in 4.0 Beta, maybe could be fixed to tighten user experience

- PackEdWPF: Trashing in package with no core.package import causes crash.
- PackEdWPF: Imports don't refresh tree layout when cloned, metadata changed to move the link

**Comment by Mgamerz** [comment]
Tpf tools still needs an icon right?

**Comment by Mgamerz** [comment]
- PackEdWPF: Right clicking blank spaces in the tree (where the tree is not displaying an item, e.g. a small file) the right click menu still appears. It should only appear when a node is clicked, not any part of the treeview.

**Comment by Mgamerz** [comment]
Item 1 on this list was fixed a few days ago.

I would need a reproducible sample from item 2. I have changed export links to new (not expanded yet) trees. I haven't tested imports - I suppose I should check that too.

**Comment by Mgamerz** [comment]
Item 2 should now be fixed in Beta branch.
