### ISSUE TITLE
Remaining 4.0 - issues

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#124]
Here is a list of things that I know of that I want to have fixed/implemented by 4.0:
 - ~~The sound samplerate dialog when replacing audio in ME3 needs to be updated to look appropriate. It also needs testing to ensure it works when replacing a 32000 item with a file at 32000 option. The default used to always be 24000, and still is, but 32000 is now an option~~
 - ~~Saving (Ctrl S) in Sequence Editor WPF seems like it doesn't always work. You hear a "ding" from Windows indicating its not supported. I am unsure if this is InterpreterWPF intercepting it (it doesn't use ctrl s) when focused, or the context menu, or something else, but I am finding it very common.~~
 - The "Last saved at..." I think should be a user control, and when the file is saved, it should do something to indicate something has changed beyond change text. Maybe flash green background and then fade to transparent over the course of like .5s - something visible to tell the user something has happened. It seems very easy to forget to save is what I have noticed while dogfooding it for my mod
 - Check for duplicate indexes code needs to be updated - I am not really sure what determines a duplicate index. It seems like attached components don't? By they do sometimes?
 - ~~Multi drop relinking needs to ensure all dropped items are from the same file, or it will relink things wrong~~
 - ~~Soundpanel: HIRCs tab needs testing. I should change the listed items on the right to a list box that can be clicked on to highlight those bytes.~~
![image](https://user-images.githubusercontent.com/2738836/57864053-74df7480-77b8-11e9-9307-749d5e1043b6.png)
 - ~~Sequence Editor WPF: "Remove from sequence" right click menu option needs a few things done to it:~~
   - ~~Only show if relevant~~
   - ~~Ensure all incoming links are removed, or notify user that incoming links will be removed~~
   - ~~This is very useful feature because kismet logger can get really cluttered if there's a bunch of worthless triggers that are no longer hooked up~~
 - ~~Package Editor WPF: When cloning an object, the metadata panel for some reason has 2 items that go blank. I can't figure out why. If you click away and back they're fine, but I don't know why. Maybe someone can look into this, part of MetadataEditorWPF.xaml.cs.~~
 - ~~Interpreter WPF: Hide/show array move options as they are relevant~~
 - Curve Editor: Doesn't always consistently modify the export. I think it has to do with the code that would prevent tons of writes as the user dragged the point. Seems inconsistent.
 - Binary Interpreter returning to the previous selected item would be useful, currently it selects but doesn't come into view

**Comment by Mgamerz** [comment]
~~Additional issue: InterpreterWPF: Sometimes the boolproperty true/false dropdown becomes blank and seems to fall back to editable style. I find this happens quite often when I am doing something like adding bClientSideOnly to a LevelLoaded event in sequence editor, after doing things a few times in that tool, the list becomes blank (with 2 invisible values). Selecting the top is still true, the bottom is false.~~

**Comment by Mgamerz** [comment]
~~Additional issue: Editing metadata for import in imports view doesn't refresh the import's data in the import list view. likely needs some property change notifications somewhere.~~

Edit: Just kidding, this is actually implemented, I just had too long of a package path to see it.

**Comment by Mgamerz** [comment]
~~Additional issue: Metadata editor (imports view): Adding name (press enter when typing in a new name) shows dialog, pressing enter with new value (instead of OK) doesn't seem to return the value reliably. It also sets the value to blank, but the name is added.~~

**Comment by Mgamerz** [comment]
~~Package Editor WPF: Having a search term in the search box, then pressing CTRL+O and then pressing Enter to select the file in the dialog will result in an exception as the search box is also interpreting a keyup event.~~

**Comment by Mgamerz** [comment]
Binary Interpreter WPF should support background scan cancellation. I made the mistake of opening the global shader cache and watched 32GB of ram disappear before my eyes.

**Comment by Kinkojiro** [comment]
I looked at the HIRC tabs yesterday.  Apart from the issue (fixed) with the float not being visible on the hex bar, it seemed fine.  It still doesn't replace Wwisebank editor because you cannot clone HIRCs but apart from that it is good.

**Comment by Mgamerz** [comment]
Since I am not intending to replace WwiseBankEditor in 4.0, I will close this for now. We will look at this in 4.1.
