### ISSUE TITLE
Header errors in cloned objects.

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#127]
[headererrors inside pcc.zip](https://github.com/ME3Tweaks/ME3Explorer/files/3232875/headererrors.inside.pcc.zip)

**Describe the bug**
Header errors within SeqVar objects I've cloned directly from Sequence View and then relinked in package editor WPF.

**To Reproduce**
I'm unsure of what caused it, since I discovered the issue later when browsing with package editor.
1. Go to Main sequence, james, investigate
2. Click on any "Player" SeqVar variable and clone it from within Sequence view.
3. Open in package WPF manager, unlink from sequence by removing the object reference from sequence and use metadata editor to relink it to the Ambients_Dialog sequence of James.
4. Add it to the sequence reference of Ambients_Dialog.

**Expected behavior**
At some point in this process, I had created about 7 clones from Investigates to Ambients_Dialog this way, and all of them give a popup-error when selecting them, saying that there is a header-error. I suspect it's the meta-data editor that has some fault. Maybe I forgot to de-reference it before moving it, but I can't remember and it should not cause header errors.

**Screenshots and files used to replicate this**
![billede](https://user-images.githubusercontent.com/17158981/58563761-feb52600-822b-11e9-8712-213ddc44437c.png)

**Version information:**
Using build 5.21.2019

**Comment by Mgamerz** [comment]
Do you get these header error messages in the WPF version of package editor?

**Comment by Mgamerz** [comment]
The superclass and archetype values in your cloned objects are invalid. They point to -83, which is the next import if it existed. I am unable to reproduce this issue, I cloned in Sequence Editor WPF and then modified the link in Package Editor WPF. Your picture shows you are not using Package Editor WPF and are using Package Editor Classic, which we are no longer supporting. Even with your invalid values, Package Editor WPF does not have issues showing the values, however these values for sure will not work in the game.

You can remove sequence objects by right clicking them.

**Comment by linkenski** [comment]
This was the classic version but as you say the values wouldn't work. I suppose the issue sprung from me not realizing that classic was deprecated in 4.0.0.

**Comment by linkenski** [comment]
You should close this. Seems like the header errors came from not always updating the parent sequence automatically when selecting a new link for an export.
