### ISSUE TITLE
Adding array element to a Node_Sequence(Sequence) brings an error, because the new element is empty.

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#129]
**Describe the bug**
If you select "Add Array Element" to a Node Sequence the element is added but comes with a popup error, telling you that the index is out of range. In older versions of ME3Explorer, you can define what you're adding and then click "add" afterwards but not in the WPF version. Regardless it seems like there's an exception that gets caught here.

**To Reproduce**
Go to any LOC_INT file, and do the following:
1. Go to its Node Sequence of any conversation tree
2. Click on "Add Array Element"
3. See error.

**Expected behavior**
It gives a popup error describing what sounds like a null exception but continues.

**Version information:**
4.0.0, 5.21

**Comment by Mgamerz** [comment]
Please include specific reproducible steps - `Go to its Node Sequence of any conversation tree` does not tell me what I actually need to do to reproduce this. What is a Node Sequence of any conversation tree?

Filenames, export numbers, tools, etc.
