### ISSUE TITLE
Update the tree-view when setting an array element to a node-sequence.

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#130]
Adding a new Array Element to a Node Sequence places a new element with null in.

When you then Set the Export reference to it, you have to manually update Tree view by deselecting the sequence by clicking on another export and then back again, or it still displays "Null" in the element you set.

**Comment by Mgamerz** [comment]
Please include reproducible steps, as I don't know what tool you are talking about.

**Comment by Mgamerz** [comment]
I am not sure what a node sequence is. Please include reproducible steps.

**Comment by SirCxyrtyx** [comment]
I assume you're talking about the fact that Sequence Editor freaks out when there's an invalid export in a Sequence's SequenceObject array. That's a legitimate problem, which I am fixing. However, you shouldn't be adding an array element to the the SequenceObject array. If you want to add an object to the sequence, use the Add Object menu item, which can be accessed via the tools menu, or by right-clicking a blank spot in the sequence graph.
