### ISSUE TITLE
Pathfinding Editor WPF: Need node description as part of database

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#131]
Pathfinding Editor WPF uses the pathfinding database (located in the exec folder) to display node descriptions. Currently it is pretty sparse and could use descriptions of different types of pathfinding nodes so users can tell what a node is designed for. Such as an SFXNav_TurretPoint for placing Cerberus Turets, Geth Prime Turrets, and Collector Webs.

**Comment by Kinkojiro** [comment]
List has been reordered alphabetically to make easier to see what has been added already.

Unadded classes used in game:

- [x] DoorMarker
- [x] SFXDoorMarker
- [x] SFXDynamicPathNode
- [x] SFXNAV_JumpNode
- [x] SFXNAV_KaiLengShield
- [x] SFXNAV_LeapNodeHumanoid
- [x] SFXNAV_LeapNodeLarge 
- [x] SFXNAV_SpawnEntrance

In specific files:

- [x] SFXNAV_HarvesterMoveNode
- [x] SFXNAV_InteractionCannibal
- [x] SFXNAV_InteractionCenturion
- [x] SFXNAV_InteractionGuardPose
- [x] SFXNAV_InteractionHusk
- [x] SFXNAV_InteractionInspectOmniTool
- [x] SFXNAV_InteractionInspectWeapons
- [x] SFXNAV_InteractionListening
- [x] SFXNAV_InteractionListening2
- [x] SFXNAV_InteractionOmniToolScan
- [x] SFXNAV_InteractionRavager
- [x] SFXNAV_InteractionSniperSweep
- [x] SFXNAV_InteractionTalking
- [x] SFXNAV_InteractionTalking2
- [x] SFXNAV_InteractionTalking3

Unused in Engine/SFXGame:

- [ ] SFXNAV_ActionStationWP
- [ ] SFXNAV_BlockingPathNode
- [ ] SFXNAV_ForcedPathNode
- [ ] SFXNAV_InteractionPoint
- [x] SFXNav_LeapNodeBase
- [ ] SFXNAV_GoalPoint
- [ ] SFXNAV_PlayAnimWP
- [ ] SFXNAV_Waypoint

**Comment by Mgamerz** [comment]
I don't see a commit for this yet? Did you do a pull push?

**Comment by Kinkojiro** [comment]
I have done all the ones in game via commit f703c05b.  I leave it up to you whether you want the ones that are only in sfxgame/engine for completeness.

**Comment by Mgamerz** [comment]
I think that is good for now, thanks.
