### ISSUE TITLE
Better display of entry indexing in toolset

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#132]
**Describe the bug**
Exports and Imports are indexed along the full package path, rather than just the leaf entry. The UI does not reflect this currently anywhere and almost all of the underlying code does not use indexing as part of its path resolution for entries.

**To Reproduce**
N/A

**Expected behavior**
UI and toolset should account for indexing as part of the paths for entries

**Screenshots and files used to replicate this**
N/A

**Version information:**
Everything before 4.1

**Stack trace**
N/A

**Other information**
This will require significant rearchitecting as GetFullPath is used a lot and changing what it returns will potentially cause a lot of bugs until the code using it is corrected.

**Comment by SirCxyrtyx** [comment]
Resolved in cc6303691a60c21a4b88f42dee59361a069f873d
