### ISSUE TITLE
"Too many children to display" in large sequence

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#135]
**Describe the bug**
In package editor it says "Too many children to display" for the sequence object array in Exp 6701 nor_joker_bridge_d_d(package)'s Node_Data_Sequence, and attempting to either add array elements through the editor or sequence editor's clone features will lead to exceptions.

**To Reproduce**
In the file I've sent...
1. Go to 'Exp 6701' and locate its 'Node_Data_Sequence'
2. Click on its 'SequenceObjects' array and expand.

**Expected behavior**
It will say 'Too many children to display' and you will not be able to see the 1300-something elements it contains. In the file I've sent there's about 7-ish added exports from cloning.

**Screenshots and files used to replicate this**
![billede](https://user-images.githubusercontent.com/17158981/59556676-c4d37600-8fc6-11e9-83f1-11ddb5ce4bb8.png)

**Version information:**
In version 4.0.1, 6-11-2019

**Stack trace**

This is what happens when you try to link an outputlink of an interp I cloned from Sequence Editor to an EndCurrentConvNode I cloned from sequence editor:

--Begin--

************** Undtagelsestekst **************
System.ArgumentOutOfRangeException: Længden må ikke være mindre end nul.
Parameternavn: length
   ved System.String.Substring(Int32 startIndex, Int32 length)
   ved ME3Explorer.SequenceObjects.SBox.CreateOutlink(PNode n1, PNode n2)
   ved ME3Explorer.SequenceObjects.SBox.OutputDragHandler.OnEndDrag(Object sender, PInputEventArgs e)
   ved UMD.HCIL.Piccolo.Event.PDragSequenceEventHandler.OnMouseUp(Object sender, PInputEventArgs e)
   ved UMD.HCIL.Piccolo.PNode.HandleEvent(PInputEventArgs e, PInputEventHandler handler)
   ved UMD.HCIL.Piccolo.Util.PPickPath.ProcessEvent(PInputEventArgs e)
   ved UMD.HCIL.Piccolo.PInputManager.DispatchToPath(PInputEventArgs e, PInputType type, PPickPath path)
   ved UMD.HCIL.Piccolo.PInputManager.Dispatch(PInputEventArgs e)
   ved UMD.HCIL.Piccolo.PInputManager.ProcessInput()
   ved UMD.HCIL.Piccolo.PRoot.ProcessInputs()
   ved UMD.HCIL.Piccolo.PCanvas.OnMouseUp(MouseEventArgs e)
   ved System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   ved System.Windows.Forms.Control.WndProc(Message& m)
   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Other information**
Trying to add cloned exports through sequence editor by right-clicking and selecting "Add Export" works, but connecting seemingly anything returns ArgumentOutOfRange exceptions.
[BioD_Nor_201Bridge_LOC_INT.zip](https://github.com/ME3Tweaks/ME3Explorer/files/3293579/BioD_Nor_201Bridge_LOC_INT.zip)

LOC_INT file attatched: Contains edits to the BioConversation at Exp 478 and as mentioned, 7+ cloned exports in the Sequence of the corresponding package.

**Comment by Mgamerz** [comment]
@SirCxyrtyx It seems the code in sequence editor here is incorrectly assuming varlinks will always have an element in it. It is accessing the 0th index of an empty list. Looking at the code I am not sure how to handle this so I will leave this up to you. I am able to trigger this simply opening a sequence in the provided file.

**Comment by Mgamerz** [comment]
Looking at it a bit closer, dragging links doesn't seem to do anything either. Not sure if it is related to this initial bug at the start.

**Comment by Mgamerz** [comment]
@SirCxyrtyx Did you mean to close this with your commit? (Fix \#NUMBER in a commit message will mark one as fixed, as will close)
