### ISSUE TITLE
PkgEd: renaming classes breaks enum parsing

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#136]
In Package Editor WPF, renaming parent class breaks enum parsing and inheritance tree (from AddProperty window) of child if it's also renamed.

Screenshot of example file. First is without renaming, and second - with.
![_bugME3Ex](https://user-images.githubusercontent.com/44444384/59565515-f5fa8780-9054-11e9-91d4-5671785f372c.png)

File from the screenshot (after modifications).
[SFXWeapon_SniperRifles.zip](https://github.com/ME3Tweaks/ME3Explorer/files/3294220/SFXWeapon_SniperRifles.zip)

It's the same issue on other files.
I'm using version 4.0 with date of 6-1-2019

**Comment by Kinkojiro** [comment]
This has to do with the very high level working of how ME3Explorer parses properties.  It looks up classes from SFXGame and a database of classes.  But it doesn't regather all that information by looking through superclasses and up the tree of data.  I suspect that would be quite inefficient.  For custom classes I have created I either have to manually add them to the database or just use a workaround -> rename your new class "SFXMassCannon_Renamed" back to its original or a sibling class.   

It will then pick up all the custom enum and other properties.  Just before you test don't forget to rename it back.  It is not a perfect solution, but I doubt we can do better without a substantial rewrite of the entire toolkit code.

**Comment by Mgamerz** [comment]
I have significantly rewritten how lookups were done since 3.0, I think I
just need to add recursive on the fly lookups so the parents can also be
resolved.

**Comment by SirCxyrtyx** [comment]
Sorry this took so long, but it's finally fixed.
