### ISSUE TITLE
Show nLineStringRef strings for FOVO objects

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#137]
//I AM USING VERSION 4.0.1 BUILD 6-11-2019! AAAH//

In older versions of the toolset the string line would be displayed next to the ID of SFXInterpTrackPlayFaceOnlyVO objects.
![billede](https://user-images.githubusercontent.com/17158981/59659230-1128dc80-91a6-11e9-85cf-1d60adf775cc.png)

It don't no more :(

**Comment by Mgamerz** [comment]
Include.

Version.

Information.

I did not write up the issue templates for nothing.

**Comment by linkenski** [comment]
It's in the edit.

**Comment by Kinkojiro** [comment]
This is because, unusually, that structproperty reference is an intproperty rather than a strrefproperty.
