### ISSUE TITLE
Euler and raw value displays, and toggle swapping them.

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#140]
**Is your feature request related to a problem? Please describe.**
Certain Kismet objects containing euler rotation values (X Y Z) take inputs in euler formats (degrees relative to an anchor) calculated from raw unreal values. Due to certain ways Mass Effect 3's cameras display information with debugging, it would be intuitive to be able to have the option to toggle between inputting in "raw" format or "euler" format for various ME3 objects in Kismet and Package editor.

![billede](https://user-images.githubusercontent.com/17158981/59965627-0c9b5580-9511-11e9-9ee3-7263a8ff7ddd.png)

**Describe the solution you'd like**
Using the example above, which is of a SeqAct_Teleport object, it displays inputs in raw format, but stores the value in euler. Being able to swap the input value and displayed converted value when you're trying to use a raw value from debugcamera, for example, would speed up the process of locating objects or positions in-game and assigning that data to your modified objects.

**Describe alternatives you've considered**
Like we have "Hex converter", a new tool in a similar detatchable window, a "Unreal Rotation Converter" that takes degrees and outputs in raw, or vice versa. It would help tremendously for many who haven't memorized the way it's calculated.
Secondly, the way this SeqAct_Teleport object displays the conversion would be neat to have inside InterpTrackMove objects in Package Editor (displaying raw in parenthesis of the euler).

**Additional context**
Recently I was trying to edit a camera for a BioConversation and used command ToggleDebugCamera to screenshot locations to copy and paste into the camera data. You have to be able to convert the raw data from this camera into euler since most rotation values inside of UE3 Kismet or at least ME3Explorer rely on this format and not raw data.

If you want to check a SeqAct_Teleport I know there is one in BioD_CitHub_Embassy.pcc in "Kalisah" sequence.

**Comment by Mgamerz** [comment]
Now that Hex Converter does unit conversions, can this be closed?
