### ISSUE TITLE
Mysterious interptrack issue (and trashpackage)

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#141]
**Describe the bug**
InterpViewer started complaining that an export InterpGroup is faulty. I ultimately cloned a seperate interpgroup and relinked its interptracks, and trashpackaged it, but it seems to be complaining about said package despite me removing it from interptrack references.

**To Reproduce**
Open the file, and try to open InterpData 1484 (1-indexed).

Try opening InterpTracks and removing element 5242, then save or open this InterpData in InterpViewer.
I get this error.

**Expected behavior**
![billede](https://user-images.githubusercontent.com/17158981/60056654-ed075700-96e1-11e9-9966-b264ad893709.png)

**Version information:**
6-17-2019 Nightly

[BioD_KroGar_212CampConv3_LOC_INT_TrashPackIssue.zip](https://github.com/ME3Tweaks/ME3Explorer/files/3322825/BioD_KroGar_212CampConv3_LOC_INT_TrashPackIssue.zip)

**More info:**
Look at the root for the trashpackages. I accidentally trashed them before removing them from InterpTracks (I did afterwards) but it seems some hex, header data, whatever it might be, still considers the main Trashpackage to be connected with something in the InterpData I pointed towards. I've tried a few things with the Lighting InterpGroup, a clone, which caused this to happen. I can't figure out what went wrong this time.

**Comment by SirCxyrtyx** [comment]
Look at Export 1700 (InterpGroup). It's InterpTracks array has one of the exports you trashed in it.
