### ISSUE TITLE
Mount Editor: loading file from other game doesn't refresh flags list

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#142]
Loading file from game different then current selected ('ME2 Mount file' checkbox) will update the checkbox, but won't update DLC Mount Flags dropdown list, therefore showing wrong values.

Example: I had ME3 mode selected by default (checkbox value == false). Then I loaded ME2 file and it changed checkbox value to true (= ME2 mode) automatically, but mount flag list didn't refresh and it still shows ME3 flags to select. It also writes that wrong flag when I save file.
Checking and unchecking mode manually does refresh the list, but at the same time, loses value loaded from file.
To get it correct reading, I have to set ME2/ME3 mode before loading the file.

Checked in versions 4.0 6-1-2019 and 4.1 DEBUG 6-29-2019

**Comment by Mgamerz** [comment]
I'll take a look at this in the next couple of days.
