### ISSUE TITLE
Package Editor WPF Text with Windows Dark Theming

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#148]
Issue: Currently, Package Editor WPF displays black text on imports and exports if you choose a dark theme. @Mgamerz told me its because Package Editor does not use system colors and told me to paste this from discord.

```public System.Windows.Media.Brush ForegroundColor
        {
            get => Entry == null ? System.Windows.Media.Brushes.Black : UIndex > 0 ? System.Windows.Media.Brushes.Black : System.Windows.Media.Brushes.Gray;
            set
            {
                _foregroundColor = value;
                OnPropertyChanged();
            }
        }
```

Proposed Solution: Make it so that Package Editor WPF uses system colors. If possible, have the hexbox be dependent on system colors as well.

Here is a screenshot of what WPF looks like with a dark theme now.
![Capture](https://user-images.githubusercontent.com/54486002/65303372-dd19da80-db4b-11e9-8333-6bd10d0dc010.PNG)

**Comment by Mgamerz** [comment]
For documentation purposes, this is an issue with your custom windows theme, not the official Windows Dark Theme. It cannot theme our application in certain areas as we hardcode the colors rather than using system defaults, which at times is required for the application to look appropriate.

**Comment by scottina123** [comment]
@SirCxyrtyx  looks like the export import and names tab is still showing black text. Can anything be done about this?

![ME3Explorer_2019-09-24_23-09-01](https://user-images.githubusercontent.com/54486002/65566548-3bb2d000-df21-11e9-88a8-dd00eab5bb52.jpg)

**Comment by Mgamerz** [comment]
This should be fixed now, please try build from #me3explorer_autobuilds channel once this commit's build has completed.
