### ISSUE TITLE
Package Editor Improvements

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#149]
These are feature requests that I posted on Discord for Package Editor

1) ~~Currently we can search for exports by class. Is it possible to expand by this by having package editor search for all exports of a specific class and showing them a list like the changed exports between files list?~~

2) ~~For those two lists, is it possible to add a right click option to go to the changed export?~~

3) ~~Is is possible to add a hotkey for add name in package editor. I add a lot of names to packages so this would save me a bunch of time. Something like Control 1 would work best for me~~ CTRL-A

4) ~~Would it be possible to clone an export and its tree more than once in once click? This would save me a buch of time because I clone a lot of actors, materials, etc when I edit a level. Intervals of 2, 5, and 10 would probably be best.~~

5) ~~Add a remove from persistant level option in the context menu for children of the persistant levels. For example, I had to remove a couple of bugged vanilla skeletal mesh actors from a pcc. Not having to scroll back up to the persistant level would be a huge QOL improvement. Similarly, it would be great to remove the child from the persistant level automatically if you trash the child for any reason.~~

6) ~~Have an option to open Meshplorer WPF from Package Editor.~~
 - Done

**Comment by mirh** [comment]
The list could be improved visually with a [task list](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown). 
Also, if I may suggest.. Some kind of non-hex editing ability? As far as feasible I mean, for example even just being able to nop/remove a line of a script (or a variable within it) would be leaps and bounds for user friendliness.

**Comment by Mgamerz** [comment]
Bullet point 2 was just implemented by 2c4c66654009862c4698b17781c37162f5fc005a
