### ISSUE TITLE
Conditional Editor Overhaul

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#150]
Feature request from the ME3Tweaks Discord

Currently the Conditional Editor is very unintuitve to use compared with the rest of the toolset.

Ideas for improvements

1) Move all functions from the edit menu to a context menu when you right on the conditional. This keeps things in line with Package Editor.

2) Have a way to generate a new CND. The current workflow for making a new CND is taking an existing one, deleting the existing conditionals and the renaming the file. Even with a DLC CND, this is cumbersome.

3) Make it so that you can add new conditionals even if the CND is blank. Currently you can't truly add new ones. You have to clone them. The propesed generator would have to account for this.

**Comment by linkenski** [comment]
I want to add, there's certain operators that will be autocorrected into simple ones. I'll get back on this once I catch which, but I had a conditional expression which I literally copied, while adding something to it, and the special operaters got converted back to simpler ones. (times, subtraction etc.)

**Comment by henbagle** [comment]
Closed, implemented in LEX
