### ISSUE TITLE
Script Editor Enhancement: highlight point where Jump call points to

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#151]
Currently, there's no easy way of finding where in the code Jump calls (eg. EX_Jump, EX_JumpIfNot) are pointing to.
Decompiled script only shows that position as a number, to be worse, in decimal, and to be even worse, from start of actual script (i.e. after Script Size integer), not from start of hex table display. As such, finding that point is really tedious.
![obraz](https://user-images.githubusercontent.com/44444384/66703594-8f405e80-ed14-11e9-8a31-af3a6bfdfa04.png)

As an enhancement, option to somehow easily show the user the point of that Jump would be really useful. While I'm not sure of implementation method, the one I though of is lightly highlighting relevant line of code in some color when user click on the Jump call.
Some professional Paint:
![wgsgfrr](https://user-images.githubusercontent.com/44444384/66703655-286f7500-ed15-11e9-8e38-3d8bcd8cd53f.png)
This implementation method is only a proposition though. Really any other option that works and would be better in eye of dev would be enough.

Currently using newest Nightly 10-12-2019. I only checked on ME2 scripts.

**Comment by Mgamerz** [comment]
This is something that will be part of our script editing refactoring. I am not sure I will have time to do it properly for the next release but I might be able to hackjob something in. 

We plan to do a fairly extensive overhaul of script parsing in the next big release after this one.

**Comment by Mgamerz** [comment]
Implemented via a5520795c86dcd92811e62167b1c3b663d056661.
