### ISSUE TITLE
Pathfinding Editor Bugs

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#152]
When trying to clone a node in pathfinding editor, the tool just locks up and freezes. To replicate open any file and try to clone a node. This screenshot below is what I get everytime I try to clone one. The UI just vanished and I get the loading mouse icon. Tested on 4.1 nightly 10/10

![ME3Explorer_2019-10-14_14-56-33](https://user-images.githubusercontent.com/54486002/66775974-4bc02e80-ee93-11e9-9f62-243097073c1a.jpg)

**Comment by scottina123** [comment]
There also seems to be one other issue. I am using 4.01 in the screenshot below, so apoligies for it looking bad. 

When cloning an actor with multiple child items, in pathfinding editor, it seems like it only clones the first child. Export 13929 and its children is what its supposed to clone. Export 13937 is what it actually creates.
![ME3Explorer_2019-10-14_15-06-08](https://user-images.githubusercontent.com/54486002/66776505-84143c80-ee94-11e9-8eb2-b306fc8aa586.jpg)

**Comment by Mgamerz** [comment]
Node cloning was a feature that predated package editor wpf clone. IT was designed around idea of only one subchild, since it was originally designed only for nodes.

We can probably change it over to Package Editors implementation.
