### ISSUE TITLE
List of minor things to fix for 4.1.1

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#153]
**Package Editor**
~~- MetaData - save hex changes  should read "Save All Changes"~~ Fixed 1a4a2b2a
~~- ShaderCache porting => check out bad cache port from BioD_Nor_100CabinDLC (omega dlc)
{porting causes file to crash game}~~ Unable to fix

**FaceFXEditor**

~~- Doesn't seem to save properly/share changes with rest of toolkit.~~ Fixed 4c5ce4709dbae804ced26e6cd4a84fdb9da9aed8
~~- When copying lines into tab view it doesn't save them at all.~~

**Dialogue Editor**
~~- refresh Interpdata when exportID changes~~ Fixed c0119f6
~~- open the wwisestreams in packed button~~
~~- open the convo in packed button~~

**TLK Manager/Editor**
- TLK Editor for ME2/ME3 needs improved in fileexportloader and exportloaderhostedwindow - Mostly done. Needs just a bit more work like hiding or updating how MODIFIED is shown.

**Soundplorer**
~~- Playing a wwisestream doesn't seem to lookup the afc unless it is in the local directory.~~

**Sequence Editor**
~~- Object Instance Version => ActivateRemoteEvent and SeqEvent_RemoteEvent are incorrect. Both show 1, where it should be 3 and 2 respectively.~~

Few other things to do:

- Check for memory leaks. I am almost certain new export loaders have memory leaks. Package dumper retains significant memory too after completion
- Make ASI manager use Mod Manager's installed mod system to detect improperly named ASI so you don't try to add new ones
- Add Ace Slammer ASIs to ASI server manifest (I will move this to github for the following release). -ME3Exp Interop will be added in the following release.
- Make TFC compactor compact files after compaction to re-arrange the export tables
-  SeqAct_Log Enabler to the ASI manifest too.

If anybody has any other minor things that need fixing, please let me know.

**Comment by Mgamerz** [comment]
- TLK Editor for ME2/ME3 needs improved in fileexportloader and exportloaderhostedwindow

**Comment by SirCxyrtyx** [comment]
FaceFX issues fixed in 4c5ce4709dbae804ced26e6cd4a84fdb9da9aed8

**Comment by Kinkojiro** [comment]
Added another small thing:

**Soundplorer**
- Playing a wwisestream doesn't seem to lookup the afc unless it is in the local directory.

**Comment by Mgamerz** [comment]
This was fixed in beta branch a few days ago. It is not in your branch.

**Comment by Mgamerz** [comment]
Few other things to do:
 - Check for memory leaks. I am almost certain new export loaders have memory leaks. Package dumper retains significant memory too after completion
 - Make ASI manager use Mod Manager's installed mod system to detect improperly named ASI so you don't try to add new ones
 - Add Ace Slammer ASIs to ASI server manifest (I will move this to github for the following release). ME3Exp Interop will be added in the following release.
 - Make TFC compactor compact files after compaction to re-arrange the export tables

**Comment by SirCxyrtyx** [comment]
Should add the SeqAct_Log Enabler to the ASI manifest too.
