### ISSUE TITLE
Automatically add a cloned sequence and LSK to the main sequence object list and Bioworldinfo 

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#158]
Is it possible to automatically add a cloned sequence to the main sequence object list like what was added with actors and the persitant level?

Automatically adding cloned level streaming kisemts to the bioworldinfo streaming level list would also be greatly appreciated.

Finally, if you trash a sequence or LSK, it would be nice to have them automatically removed from those lists like what was done with trashing actors.

**Comment by Kinkojiro** [comment]
Cloning sequences in Sequence Editor automatically adds them to the sequence that they are cloned to.   Similarly when trashed in sequence editor. So just use SeqEd for editing sequences. 

For LSKs there is a tool in Package Ed Convenience Tools which will rebuild the streaming kismet list automatically.  Just use that after cloning or trashing.
