### ISSUE TITLE
Cloning a Tree Does Not Link the New Children to the Cloned Parent

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#159]
When cloning an object, the new parent does not link to the the newly cloned children. The new export links back to the original children. 

To test, clone any tree an look at what the stuff in the interperter links to.

Tested on 11/29 Nightly. Seems like the issue happened sometime after the 11/23 nightly

**Comment by Kinkojiro** [comment]
I can confirm this issue.

My guess is this is something to do with merge of LiveEditor into Beta  82718ffc
but I don't understand enough to fix it.
