### ISSUE TITLE
Feature update/bug: Wwise editor does not update bank/hex size when hex editing

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#16]
If you clone an object in Wwisebank then the wwiseeditor updates various counts and lengths:
(1) Bank (pre BNK) length x2
(2) HIRC header (post HIRC) length, count

However if you hex edit the length of an individual object (for example copy hex from Bank A and overwrite a new cloned object in Bank B) the lengths are not updated resulting in a crash.

**Comment by Mgamerz** [comment]
Can you post a file with instructions on how to reproduce this issue?

**Comment by Kinkojiro** [comment]
Posted on discord

**Comment by Kinkojiro** [comment]
Fixed ty
