### ISSUE TITLE
InterpViewer right-clicking

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#160]
I'm missing the old function to right-click on the interpgroups inside InterpViewer and select "Open In Package Editor".

I don't know the limitations of using WPF and right-clicking, but it seems the function was omitted or forgotten after the new package-view was added, but for bigger tasks it's less convenient to use the viewer, so either right clicking or shift/CTRL-clicking opening up and locating the InterpGroup inside Package Editor would be nice.

Using version 4.1.1.314

**Comment by Kinkojiro** [comment]
Option added in commit 00ed3f82
