### ISSUE TITLE
Cannot clone HIRC objects in PackageEd sound tab

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#162]
If you go to a WwiseBank object inside a .pcc file (easily located in BioSnd files) and go to the "sound" tab, and then "HIRCs" you cannot right click to clone an object as in WwiseBank Editor.

**Describe the bug**
Right click is missing. No ability to select "Clone Object" or "add HIRC".

**To Reproduce**
Open a BioSnd file and open one of its "Streaming" or "Non-streaming" packages. Inside it, select a file of the class "WwiseBank" and then go to the Sound Tab next to Binary Interpreter. Go to HIRCs inside that and select an object in the list. Right clicking it has no functionality, leaving you unable to add and edit a HIRC object.

**Expected behavior**
No popup will appear upon right clicking.

**Screenshots and files used to replicate this**
![billede](https://user-images.githubusercontent.com/17158981/72627794-6354fa80-394d-11ea-8862-86a08c31d97b.png)

**Version information:**
Using Version 4.1.1 11-12-2019

**Comment by Kinkojiro** [comment]
I have done extensive sound editing from within the tab.  I think this can be closed.
