### ISSUE TITLE
Non-ME3 script decompiling produces less elegant code

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/LegendaryExplorer#165]
This is very minor issue, but still if you have time to spare..

**Describe the bug**
For example, compare this (in PlayerInput.PlayerInput of both ME1 and ME2)
```
aUp * TimeScale * MoveStrafeSpeed
```
with this from ME3
```
aUp *= (TimeScale * MoveStrafeSpeed)
```

Also, I'm not sure why ME3 lines begins with "*offset:*", while other games get "*offset* | "

**Version information:**
4.11

**Comment by Mgamerz** [comment]
The decompiler system for me3 is entirely different from me1 and me2. 1/2
is based of the unhood project and 3 is based on warranty voiders work. 3
has a different bytecode system than 3, however the WPF UI was originally
designed around unhoods implementation. We plan to merge them once the team
gets back together, right now kinkojiro and sirc are away and I have been
working on various projects. I will keep this in mind when we upgrade the
me3 code for relinking.

**Comment by mirh** [comment]
Oh, ok, sorry. I didn't know there were still trainloads of changes and adjustments planned. 
I wouldn't have gone into "bug report everything even slightly amiss" mode otherwise. 
Thanks for all your efforts.

**Comment by Mgamerz** [comment]
It’s all good. I’ve put some items into our tracker that you’ve recently reported, I’ve isolated the issue but am waiting for kinkojiro to fix because they’re in his domain.

**Comment by mirh** [comment]
Well, SirCxyrtyx pulled off some magic in the new script viewer, I guess like this can be closed. 
(there's an exception thrown when you click on certain classes like PlayerInput, but I guess beggars cannot be choosers)

EDIT: fixed in last beta, though it still shows on some functions
