### ISSUE TITLE
Package Editor: Allow "Compare with unmodded" option to use Mod Manager backup

### ISSUE THREAD

**Issue by rondeeno** [ME3Tweaks/LegendaryExplorer#170]
It would be really convenient if the "Compare with unmodded" option used the Mod Manager backup (if one exists), instead of using the game directory which may have been modified.

**Comment by Mgamerz** [comment]
Please verify this is resolved for you. It's been implemented as of 4 days ago into the beta builds.

**Comment by rondeeno** [comment]
It works great, thank you!
