### ISSUE TITLE
PgEd: linking object to itselves crashes whole app

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#171]
Pretty simple thing. You can choose object's link in the Metadata tab each object has. It allows you to link to itself though.
The moment you do it, you can see the object disapperaing from tree view. Toolset might crash outright, or only when it attempts to load export list. Either way, it's bound to stop working.
Final error message translates to "A new guard page for the stack cannot be created", after using ms lookup tool.
![pN4Q5EvCIT](https://user-images.githubusercontent.com/44444384/79695002-704af800-8274-11ea-8030-90b3c68daca4.gif)

**Comment by Mgamerz** [comment]
This issue was validated as fixed on the big endian branch by Tajfun.
