### ISSUE TITLE
Meshplorer: doesn't work after launching ME3Ex with command line argument

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#172]
Title might be a bit misleding cause I can't really describe it in one short sentence.
It's pretty specific bug that's hard to explain in normal words, so list of steps to reproduce might work better here.

1. ME3Explorer.exe process is NOT running. App is fully closed.
2. You start the ME3Ex app with passing a command line argument to it containing file path. It's the default behavior when you double click on a file in windows explorer that's associated with an app. In other words: you want to open the file from WinExp. So it sends `ME3ExplorerPath "YourFilePath"` command. Eg. `I:\ME3Explorer.exe "I:\SomePCC.pcc"`. it's default Windows behavior so it doesn't need a lot of description. You can also trigger the same behavior by drag-and-dropping your PCC file on ME3Explorer executable.
3. ME3Explorer's startup method interprets the argument, opening Package Editor with this file opened. By looking at windows order in the taskbar, you can see Package Editor window has been opened before ME3Ex's main window. Besides that, everything looks alright.
4. Once ME3Ex's has been ran in previously method, bug is able to be reproduced. Now, all Meshplorer instances you will open will have broken mesh preview - it'll be blank, regardless of mesh you're trying to view. This also applies to mesh preview inside Package Editor.
5. Bug will persist as along as you don't fully restart ME3Ex - by closing it completely (i.e. making ME3Explorer.exe no longer running at all). Launching the app again while old instance is still running won't change anything.

The most important part is method of which ME3Explorer has been opened. Bug exists when ME3Explorer has been opened with file path as argument, or - in other words - was tasked to open the file at the moment of being loaded for first time.
Running another ME3Explorer processes after the initial launch won't change anything.
This is an example way on how the bug will NOT occur:

1. ME3Explorer.exe process is NOT running. App is fully closed.
2. You start the ME3Ex app by opening its exe without any additional arguments. Just clean open, done by simply clicking on the exe.
3. Everything is started correctly. Now any Meshplorer you open will work correctly, as long as the process isn't fully restarted.

It's worth mentioning that in reality only one ME3Explorer process can be run at the time - all other ones that are trying to be created will just feed the old instance. As such, running the app again with other method won't change anything without doing a full restart; because it's still the same app instance managing everything.

Checked on versions 4.1.1 11-12-2019 and 4.2 NIGHTLY 4-19-2020.

**Comment by Mgamerz** [comment]
This should be fixed by f2e89549a0235cc6f9396321968876be96b45b00. I will close this ticket once I get verification.
