### ISSUE TITLE
Meshplorer QOL Requests

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#173]
Here are some features requests for Meshplorer that would greatly benifit my workflow

1) ~~Can we have the export number next to the skeletal mesh like in pre wpf versions? This would be really helpful when adding skeletal meshes to actors.~~
![Capture](https://user-images.githubusercontent.com/54486002/79798571-35ee6300-8327-11ea-8195-3e72e52e6bbb.PNG)

2) ~~Can we have the export using umodel option in the context menu when you right click on a model?~~

3) ~~Can we have the option to right click to open the material and texture reference in package editor?~~

![Capture](https://user-images.githubusercontent.com/54486002/79798866-98476380-8327-11ea-95f5-72764d37b055.PNG)

**Comment by Mgamerz** [comment]
This should be all implemented in the latest beta. Can you confirm this so we can close the issue?

**Comment by scottina123** [comment]
everything works fine. Thanks you.
