### ISSUE TITLE
ME2 BinaryInterpreter: ChildListStart in class interpreter is off by 4 bytes

### ISSUE THREAD

**Issue by Tajfun403** [ME3Tweaks/LegendaryExplorer#178]
Small issue. In BinaryInterpreter of class packages, value of ChildListStart is being read 4 bytes earlier than it's stored.
![obraz](https://user-images.githubusercontent.com/44444384/81507528-614ce800-92fe-11ea-803a-8c073f6db066.png)

Suprisingly enough, seems like correct offset is used for automatic relinking. Therefore it seems like it's only a visual bug.

Example class used on screenshot: export 96 SFXWeapon_AssaultRifles.pcc

**Comment by SirCxyrtyx** [comment]
Unfortunately, the code used for displaying information in the Binary Interpreter and the code used for everything else (including relinking) are completely unrelated. Class parsing was updated last year, but the binaryinterpreter display code wasn't, and was innacurate in many areas. I've overhauled it completely in this commit.
