### ISSUE TITLE
Add Property Menu: Search Function

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#182]
Would it be possible to add a search function to the add property screen? It would really speed up searching for a specific property
![Capture](https://user-images.githubusercontent.com/54486002/82719478-ed54fd00-9c78-11ea-88a0-5d093986b178.PNG)

**Comment by Mgamerz** [comment]
Yeah this is on my to-do list. I have an implementation from Mod Manager that I will be porting into ME3Exp.

**Comment by Mgamerz** [comment]
See https://dev.azure.com/ME3Tweaks/ME3Explorer/_build/results?buildId=1590&view=artifacts and check to see if this works as described. The only thing that's a bit off is the interface when there are no results, but it's just a slight cosmetic issue.

**Comment by scottina123** [comment]
Search works. but package editor does not seem to allow you to add properties now

**Comment by Mgamerz** [comment]
I just commited a fix for this. It should autobuild within next hour.

**Comment by Mgamerz** [comment]
This was implemented in https://github.com/ME3Tweaks/ME3Explorer/commit/ccdc14bbbfbef25ad69202646bf68fcd6743dca6 (and fixed in a subsequent commit).
