### ISSUE TITLE
Package Editor: Importing or editing Bio2DAs causes them to break

### ISSUE THREAD

**Issue by rondeeno** [ME3Tweaks/LegendaryExplorer#184]
**Describe the bug**
When using the Import from Excel option for Bio2DAs, the table no longer appears properly in the Bio2DA tab, and none of the properties appear either. The same thing happens when editing the Bio2DA within Package Editor and pressing Commit.

**To Reproduce**
1. Open a file that contains a Bio2DA (such as Engine.u from ME1) in Package Editor.
2. Select any Bio2DA and click the Bio2DA tab.
3. Press Export to Excel and save the Excel spreadsheet.
4. Press Import from Excel and choose the newly created Excel spreadsheet.

OR

1. Open a file that contains a Bio2DA (such as Engine.u from ME1) in Package Editor.
2. Select any Bio2DA and click the Bio2DA tab.
3. Click on a cell and make an edit to it.
4. Press Commit.

**Expected behavior**
The Bio2DA's table and properties should appear properly.

**Version information:**
4.2.0.1115

**Comment by Kinkojiro** [comment]
I have run a quick test and the props appear to be created properly, but not written to the export.  I haven't looked at the new endianreader so don't understand why.

props below is created correctly:

Bio2DA, Line 347+ {Write2DAtoExport}
```              
EndianReader propsStream = new EndianReader(new MemoryStream()) { Endian = export.FileRef.Endian };
                props.WriteTo(propsStream.Writer, export.FileRef);
                MemoryStream currentDataStream = new MemoryStream(export.Data);
                byte[] propertydata = propsStream.BaseStream.ReadFully();
                int propertyStartOffset = export.GetPropertyStart();
                var newExportData = new byte[propertyStartOffset + propertydata.Length + binarydata.Length];
                Buffer.BlockCopy(export.Data, 0, newExportData, 0, propertyStartOffset);
                propertydata.CopyTo(newExportData, propertyStartOffset);
                binarydata.CopyTo(newExportData, propertyStartOffset + propertydata.Length);
                export.Data = newExportData;```

**Comment by Mgamerz** [comment]
I wouldn't be surprised if it's due to ReadFully(). This method is leftover forever ago (I think kfreonlib?) and it's name implies it does one thing when in reality it does something else. I'll look into this today.

**Comment by Mgamerz** [comment]
Additionally, it doesn't seem like it is possible to save the changes to a Bio2DA when editing it manually - the commit button never activates.

**Comment by Mgamerz** [comment]
Fixed both issues.
