### ISSUE TITLE
Issue with imported armors in ME2.

### ISSUE THREAD

**Issue by catmirandu** [ME3Tweaks/LegendaryExplorer#186]
# Please fill out the following form *in its entirety*. 
The more information you provide, the easier it will be for us to work with.

**Describe the bug**

Armors ported into ME2 (both from ME3 and original) seem to have a bug that causes issues with the animation in specific lines of dialogue.  This occurs with Femshep only.

The two issues are:

1) Either the face deforms completely (eyes popping out of the skull, face bending) during speech or
2) Facial animations seem to be "moved" from the face to a different part of the body.  (For instance, the mouth doesn't move while speaking, but the arms and shoulders bend.)

**To Reproduce**
To see the bug itself:
The bug presents using a modded/imported armor in two cutscenes we've found (so far):

First, in Kasumi's recruitment dialogue, toward the very end when she's talking to Shepard from above.  (I believe it's around the line "See you on the ship, Shepard.")
The second is at the end of Jack's recruitment mission -- when you choose the response "To rescue you" is when the facial animation bug appears on Jack.

In order to see it, equip a modded armor (one of the ones I've linked below, such as the helmetless Blood Dragon Armor -- these will show up in the Chest area and not as fully body armors) on Femshep and do the cutscene, choosing the "To rescue you" line.

To create the bug:

We have experienced it in multiple ways.  My personal way:

Cloning a PCC and using meshplorer to replace a model by importing the UPK.  For my mods, I copied the PCC that contains the Kasumi dress/tux (BIOG_HMF_SHP_CTH_R) and replaced that model, then got them into the locker by adding them in a BioGame.ini.  I've tried both the replace mesh via UPK and replace single LOD method.

My specific method always produces the second bug (moved facial animations, rather than facial deformation).

The method used to produce the facial deformations was exporting an armor from ME3 to UPK, cloning an armor file PCC from ME2 (in this case the DLC armors), and replacing the ME2 model with the ME3 model via Meshplorer.  I believe this was done via the Replace Mesh from UDK option and not "Replace single LOD from UPK."

**Expected behavior**
People talking normally.

**Screenshots and files used to replicate this**
![unknown](https://user-images.githubusercontent.com/67493175/85914170-98208400-b800-11ea-9e0f-29b324bf0927.png)
Jack facial deformation.

[Save near Jack's recruitment mission](https://www.dropbox.com/s/qr5mxmc4bfb46yu/Save_0046.pcsav?dl=0)
[Mod that includes the facial deformation bug shown above](https://1drv.ms/u/s!Ai0W644ASh1u4OIHW7EMQyVN2L5f1A?e=EgWEeV)
[Video of the facial animations not working, and the arms/shoulders moving instead](https://www.dropbox.com/s/fey3y6cnghahurn/wPLteNb7mg.mp4?dl=0)

**Version information:**
The current version I'm using is the 4.2.0.1178 6/16/2020 nightly.

**Other information**
This might just complicate matters, but here's some extra info:  I did get this to work without any bugs in one way.

I imported the mesh into an ME1 PCC using Meshplorer, replacing the default casual outfit, dragged that model from that ME1 PCC into the ME2 PCC, and it worked in this manner.  

(I did this because I'd experienced a similar issue in ME1 with the facial animations moving onto the body -- I didn't report it since changing to the single LOD method had worked there.  With one difference -- the mesh moved over slightly to the right and I had to go into 3DS max and manually move it back to the right, export it as an FBX, port it into UDK and create a UPK, then import it back into ME1 with Meshplorer using the single LOD method, and that seemed to solve the issue.)

**Comment by Mgamerz** [comment]
![image](https://user-images.githubusercontent.com/2738836/86044507-69c0c580-ba07-11ea-9ecb-1b66fe5dca96.png)
