### ISSUE TITLE
DLC .afc compactor seems unreliable.

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#189]
**Description**
The DLC audio compactor doesn't seem to always repoint the WwiseStreams in packages, of audios I changed along with edits to their Str Ref (TLK changes from my mod), so that they point to my mod's own .afc file rather than the Vanilla/DLC .afc file. This means that once I test my mod on a new install, or a new pc, a lot of my changed audios don't come with it, but for some reason only some of them did. The references aren't consistent for whatever reason.

**To Reproduce**
I make edits to the TLK file of my DLC within a range not used by the game or its DLC. First, I make an edit to the audio-file itself, then change the string reference in the names and the dialogue text to something exclusive in my TLK, (e.g. line 656776 "I'll destroy you!" becomes 3500001 "I'll kill you") and sometimes running the compactor after new changes like that (since last compact), the new changes don't count as references. It'll have 346 updates just like last time, and the file references in the packages still point to, e.g. "Exp001.afc" and not "ModInt.afc" I think it has something to do with the fact that I changed the TLK which I suppose technically turns it into "new" things. The problem then is, it's not reliable as a tool to store all DLC-specific additions or changes within. I will not notice that it hasn't caught the change, and once I vanillify ME3 and test my DLC fresh from a backup, various changed lines of dialogue will turn up empty.

**Steps to reproduce the behavior:**
1. Try unpacking TLK of your mod, add a line to become a subtitle. Repack your .xml into the mod TLK.
2. Throw some LOC_INT file of a level you can test quickly, into your mod folder, and open in dialogue-editor.
3. Go to the line you want to change, open its sound in soundplorer and replace the audio with a new wav.
4. Open the audio in package editor. Find both the WwiseStream and WwiseEvent, go to Metadata and CTRL+C the name.
5. Go to the 'Names' tab, and paste the name into the string search field. Now edit the name so that the TLK value reflects that of your TLK subtitle. Do this for WwiseStream and Event. Finally, go in the Dialogue Editor and change the Str Ref of the node, and open the InterpData in InterpViewer, change the VOElements Str Ref to the same TLK line.
6. Play the game, see that the audio has changed and string reference matches. All should be good.
7. Compact it.
8. Go see if the audio of the line now references your mod's .afc file or the vanilla/DLC .afc file.
9. Try making a change, recompact, or recompact right away.
10. Double check that the .afc file refers to your mod's.
11. Try pulling the DLC over to another computer or another game installation and check that it works on a clean install.

**Expected behavior**
12. Maybe you've encountered the problem I have. The compactor doesn't point the vanilla/DLC WwiseStreams to the mod's AFC file, and thus pulling the DLC over to a clean install won't carry over the sounds you changed according with the TLK line edits to reflect that change.

**Version information:**
Recurring issue across several versions. I have been using 4.2 Nightly 6-21-2020 build lately.

**Other information**
I may have also put a full vanilla .afc file into my mod at some point which made it save all of its content as my mod afc. It now refers to itself from what I understand (the compactor looks at what's in the mod .afc already and keeps all of that.) but something has caused it to not always update new changes to vanilla references into my mod .afc.

**Comment by Mgamerz** [comment]
This is an issue that I'll take a look into in the next week or so. AFC compactor has kind of been an experiment, I originally used it to port SP audio in bulk into MP, and it's pretty old by my coding standards. I don't really think it has anything to do with the TLKs though, as those are just object names, and my code transplanted and compacted based on offsets, it's just old code that I wrote that was originally written when I was just starting the fork.

**Comment by Mgamerz** [comment]
See https://dev.azure.com/ME3Tweaks/ME3Explorer/_build/results?buildId=1590&view=artifacts for a build that has AFC Compactor as a tool. It's not 100% done yet but it should be much more reliable. There's a few more features I want to add but haven't had time to implement.

**Comment by Mgamerz** [comment]
I've updated AFC Compactor a lot in the latest nightlies. Check it out and let me know what you think.

**Comment by Mgamerz** [comment]
Given our talks on Discord, it sounds like this new implementation is correct, but I'll hold this open for a couple days.
