### ISSUE TITLE
Suggestion: Add Spline to PathEd

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#19]
Splines are pathing components used for non-AI actors.  Typically they are using to send a walking actor around a path (e.g. the robodog on the Normandy, the walking guy in the CIC, various walkers at hubs).  They should be fairly simple to add (I would think).

The spline has an actor (singular point which is the start of the spline, it also links the chain to the predecessor spline and subsequent splines).  It has a SplineComponent which actually contains the spline data.  This is broken down like this:
Spline Info: Point 0 is the location of the Actor, Point 1 is the location of the destination (next actor)
SplineReparamableTable: This is the curve along which the actor travels: InVal is the distance along the spline and OutVal is the time along the path with 0 being the start and 1 being the end. (this can be view in Curve Editor)
Bioware always seems to break into 10 parts no matter the length of the spline.
The speed is a function of the SeqAct_MoveOnSpline / Distance.  But if the first section is say 100 units long and the second is 500 units, the actor will move unevenly (slowly then quickly).

Splines can be viewed in game with the command "SHOW SPLINES"

**Comment by Mgamerz** [comment]
Implemented in 3.0.7.
