### ISSUE TITLE
BioSeqVar_ObjectFindByName

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#2]
The object name is not displayed in Sequence Editor only ???.  Pre v2.0.10 (about) the name was displayed.

**Comment by Mgamerz** [comment]
This should be fixed by https://github.com/Mgamerz/ME3Explorer/commit/30efd6bc1a00e550be43124d06cca30e85763e4b#diff-824efb818dbd43217a307d03e2c2858dR258

Please verify if you have a chance.

**Comment by Mgamerz** [comment]
This should fix the first bullet point in https://github.com/ME3Explorer/ME3Explorer/issues/471

**Comment by Kinkojiro** [comment]
Yes that works!  Thanks MG

**Comment by Mgamerz** [comment]
Will be fully fixed when 3.0.3 releases.
