### ISSUE TITLE
Suggestion: Reordering imports of trees

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#20]
When drag and dropping trees, occasionally the import will fail if an import reference cannot be set (because it is an import with a parent that is an export package).  This is not a big deal, but it can stop the rest of the tree resolving internal links between parts of the imported tree (particularly particle systems).

The easiest fix would be to prioritise setting the classes then resolving internal tree links before working with links external to the tree.

(A) Classes get set.
(B) The code resolves the internal tree export links
(C) It attempts to resolve external object links 
That way if it fails then the tree gets setup anyway.

**Comment by Mgamerz** [comment]
Part of this issue should be resolved in the final 3.0.9 as I now attempt local lookup of exports as parents. However I am not yet satisfied with how I do cross imports on top level packages. For example if you move a wwise tree to a new file that already has the same wwise package (as they may not have the same children) it may attempt to set import links to the original package. 

I plan on making the level of the initial drop check to see if there are other items with the same name, and prompting the user if they want to merge into that instead or create a new export.

**Comment by Mgamerz** [comment]
This has been implemented, but needs checked. Merging trees is difficult as it is hard to tell item differences if the names are the same. It may be this feature will be restricted in this build until we have a more robust solution.
