### ISSUE TITLE
Rename tools to drop WPF naming?

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#203]
We have some tools that are named 'WPF', which was used when we concurrently had the winforms original and the new one, such as Soundplorer and Soundplorer WPF, Package Editor and Package Editor WPF... none of the classic versions exist anymore. Should we switch the user facing names over to remove the WPF?

![image](https://user-images.githubusercontent.com/2738836/96077902-35fe9400-0e6e-11eb-9640-6f81af7d98ce.png)

Internally they'd keep their names as there is no point in changing them.

**Comment by SirCxyrtyx** [comment]
Absolutely. Zero users know what WPF means, it's just confusing.
