### ISSUE TITLE
Exporting UDK Meshes causes Meshplorer to crash

### ISSUE THREAD

**Issue by beccatoria** [ME3Tweaks/LegendaryExplorer#214]
Attempting to export UDK meshes from Meshplorer causes the programme to freeze and crash on current nightly and stable builds. 

**To Reproduce**
I have had this issue on all meshes I have tried to export from all .pccs on, but it can definitely be reproduced with the following steps. 

1. Open BIOG_HMM_HIR_PRO_R.pcc in Meshplorer
2. Right click on HMM_HIR_Fsk_MDL (1623)
3. Choose export mesh to UDK
4. Set a name for the mesh and click save.
 
It will then freeze and then close. 

**Expected behavior**

The expected behaviour is to export the mesh and then provide a dialogue box confirming this has been done successfully.

**Version information:**
Issue exists on 5.0.2 Stable (1/2/2021) and 5.1 Nightly (1/17/2021). 

**Other information**
Works fine on the 5.0 stable release available for download from Nexus (previous files section).

**Comment by Mgamerz** [comment]
This was fixed in Beta a few days ago and is now fixed in stable 5.0.3.
