### ISSUE TITLE
TFC Compactor doesn't find installed DLC

### ISSUE THREAD

**Issue by beccatoria** [ME3Tweaks/LegendaryExplorer#215]
# Please fill out the following form *in its entirety*. 
The more information you provide, the easier it will be for us to work with.

**Describe the bug**
The TFC compactor utility does not find installed DLC, so you cannot compact any TFCs. 

**To Reproduce**

1. Install a DLC mod (this has worked with every DLC mod with a .tfc file that I've tried, but specifically, Additional Character Creation Options 1.2 for ME3 will work), 
2. Open the TFC Compactor
3. Choose the appropriate Mass Effect game in the first drop down (ME3 in the exemplar)
4. The next drop down is where you should select your DLC, but no DLCs are visible.

**Expected behavior**
In step 4. above, you would be able to select your DLC mod. 

**Version information:**
This error occurs in Nightly 5.1 1/24/2021, and in Stable 5.0.2 1/2/2021.

**Other information**
This issue does not occur in Stable 5.0 11/6/2020.

**Comment by Mgamerz** [comment]
This has been fixed in stable 5.0.3 and the latest nightly as of https://github.com/ME3Tweaks/ME3Explorer/commit/c0c3bb2ab9fcb3a16b3ac00c6e6b1fd727853f68
