### ISSUE TITLE
TLK Editor String Editing Window

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/LegendaryExplorer#220]
**Is your feature request related to a problem? Please describe.**
When there is a large string, the edit box will cover the entire window, making it impossible to switch to a different string unless you either reopen the TLK and go looking for the place where you just were or memorized the ID of a nearby string that is small enough so that you can see the list again.

**Describe the solution you'd like**
Size limit of the edit box based on the size of the window, so that a minimum of one row of the list is visible.

**Describe alternatives you've considered**
- Collapse button for edit box
- Next/Previous Buttons

**Additional context**
Large string takes up the entirety of a 1920x1080 sized window. 
![image](https://user-images.githubusercontent.com/73685731/110764459-6139b380-8253-11eb-9684-b690ce31530e.png)

**Comment by henbagle** [comment]
Closed, implemented in LEX
