### ISSUE TITLE
The Ability to Freeze the FaceFX Timeline to a Certain Size

### ISSUE THREAD

**Issue by SpaceD0lphin** [ME3Tweaks/LegendaryExplorer#221]
**The Problem.**
Currently, the FaceFX Editor's Timeline display resizes to show a phoneme/gesture's curves up to the last key only. This means when an animator is scrolling through different phoneme/gestures, the curves and timelines are all over the place, and they take time to examine, interpret and double-check. It makes adding keys for something further ahead in the line more time consuming than it needs to be, and it makes it more difficult to understand what's going on with different phoneme tracks in the same space and time.

**Solution**
The ability to standardize the timeline's display and lock it to a range defined by the user. The ability to see all keys for a given thing, whatever they are, in relation to the timeframe. If my line is 7 seconds long, I want to be able to see an overview of each individual thing, from 0-7 seconds, even if there's no information for most of that time for a given thing. So as an example, when I click through, it should be easy to see at a glance what is happening at 2.30 across everything, because I can keep my eyes in the same place.
The ability to zoom and pan would be nice. Some keys require very specific placement very close to each other. Currently, the only way to see keys in close detail is if there is only a small range of them.

**Current Workarounds**
I currently add a key at 0, and a key at the end of the audio's length for every phoneme and gesture to force the Timeline to show me everything at the same scale and length.
This is a problem because things need to be offset during creation, which then requires manual resetting of the ending key, and the longer the audio track is, the more squished everything becomes. (It's not uncommon to work on a line around 10 seconds in length or more.) I also have to remember to delete that key if it isn't actually needed once the entire sequence is complete.

**Comment by SirCxyrtyx** [comment]
Thanks for the great suggestion! It has been implemented in d58179a0604b2ed4402156d3313cb9c61a5fcd4e
