### ISSUE TITLE
Weird artifacts when replacing a static mesh in ME3

### ISSUE THREAD

**Issue by Exkywor** [ME3Tweaks/LegendaryExplorer#224]
# Please fill out the following form *in its entirety*. 
The more information you provide, the easier it will be for us to work with.

**Describe the bug**
When replacing a Mass Effect 3 static mesh, it replaces it but the mesh has weird artifacts.

**To Reproduce**
1. Open the pcc with **Package Editor**, in this case, I used base game _BioD_End002_400Guardian.pcc_.
2. Select the mesh to replace. _403 SOV_A_LowRes(StaticMesh)_ in this example.
3. Open it in **Meshplorer**.
4. Right-click the mesh and select "Replace Mesh from UDK". Select the static mesh I exported as fbx from **Blender**, converted to fbx 2013 with **AutoDesk FBX Converter**, and import it and save it as upk with the **UDK Editor**. I've followed this exact process for skeletal meshes with no problem.

**Expected behavior**
I expected the mesh to be replaced and display no artifacts.

**Screenshots and files used to replicate this**
![image](https://user-images.githubusercontent.com/46603136/111077575-0607fb00-84b7-11eb-92ae-4e4f33861f61.png)

[Before file](https://www.mediafire.com/file/9sairurhd5a9mpz/BEFORE_BioD_End002_400Guardian.pcc/file)
[After file](https://www.mediafire.com/file/us9esvsjoasvodb/AFTER_BioD_End002_400Guardian.pcc/file)

**Version information:**
ME3 Explorer 5.1 NIGHTLY 3/13/2021

**Other information**
Replacing the texture with the texture I had prepared for the new mesh does not fix the issue, and makes it even more obvious.

**Comment by SirCxyrtyx** [comment]
Could you upload the fbx and upk as well?

**Comment by Exkywor** [comment]
Yeah, sorry. Hadn't checked Github.
[FBX 2013 version](https://www.mediafire.com/file/oecysrmidr7u26k/THO_A_LowRes_%25282013%2529.fbx/file)
[FBX 2014 version](https://www.mediafire.com/file/c6hfy8xv5yj12od/THO_A_LowRes_%25282014%2529.fbx/file)
[UPK](https://www.mediafire.com/file/s5np2dz171slkgq/THO_A_LowRes.upk/file)

Blender exports the FBX in the 2014 version, then I have to convert it to 2013 so I can then convert it to UPK.

**Comment by SirCxyrtyx** [comment]
This is not a problem with ME3Explorer. Here's what your UPK looks like in UDK, so something went wrong before you imported into ME3Explorer.
![image](https://user-images.githubusercontent.com/5533111/112518776-f01bf500-8d56-11eb-8933-16070ae8788d.png)

**Comment by Mgamerz** [comment]
- [ ] Not cursed
 - [x] Cursed

**Comment by Exkywor** [comment]
Yeah, you are right. I'm gonna take a look to figure out what went wrong.
