### ISSUE TITLE
TLK Editor - Line Breaks cause "over-linebreaking" in ME2

### ISSUE THREAD

**Issue by Herobrine24** [ME3Tweaks/LegendaryExplorer#229]
**Describe the bug**
Not sure if this is caused by TLK Editor or ME2 but i think its worth investigating.

When making a string in a TLK for ME2, when using line breaks created via SHIFT+ENTER, the result in the game will have additional linebreaks. A workaround is to use `<br>` to indicate linebreaks.

**To Reproduce**
1. Create/Edit a TLK
2. Create/Edit a string with SHIFT+ENTER Linebreaks inbetween words
3. Check ingame

**Expected behavior**
One Linebreak via SHIFT+ENTER = One Linebreak ingame

**Screenshots and files used to replicate this**
SHIFT+ENTER Linebreaks for Kuwashii Visor
![image](https://user-images.githubusercontent.com/73685731/112619172-4c4e4a00-8e27-11eb-8626-c8480570567d.png)
`<br>` Linebreaks for Capacitor Chestplate
![image](https://user-images.githubusercontent.com/73685731/112619690-e7dfba80-8e27-11eb-9ade-d685cd2edcfe.png)
Mod with Kuwashii Visor Strings "335473" and "322562" using SHIFT+ENTER and everything else using `<br>`. Mod Manager Deployed 7ZIP contained within 7Z Download. Use "open biop_omghub" and go to Harrot's Emporium for Kuwashii Visor and Capacitor Chestplate
[LineBreakIssue.zip](https://github.com/ME3Tweaks/ME3Explorer/files/6211127/LineBreakIssue.zip)

**Version information:**
5.0.3
01/30/2021

**Comment by Herobrine24** [comment]
Another Workaround is to export the TLK to XML and then use the ME3+ME2 TLK Editor tool to recreate the TLK.

**Comment by SirCxyrtyx** [comment]
This was caused by Window's charming design decision to have the enter key insert both a \r and a \n. *shakes fist at Bill Gates*
