### ISSUE TITLE
FaceFX Editor: Onionskin (Viewing One Track Overlaid Atop the Other)

### ISSUE THREAD

**Issue by SpaceD0lphin** [ME3Tweaks/LegendaryExplorer#233]
**The Issue**
Many phonemes and gestures are designed to work in tandem with each other. To better allow for synchronous movements, the ability to overlay one phoneme or gesture track's view over another would be incredibly useful. It can be a pain to precisely align these shapes. The ability to view one track faintly underneath the track being edited would facilitate this process much easier.

EG: I would like to view ` Blink`'s information faintly whilst I work on `m_Jaw+`.

**The Solution**
The ability to select a phoneme/gesture track to act as the layer beneath, or the "reference layer." This should be togglable, like the "Fixed TimeSpan" box, and it should display at the same time span as the track being edited.
Crucially this reference layer should not be editable when acting as a reference. Ideally, it should also be of a different colour or a lower opacity - anything to differentiate it somehow.
If it is easier to implement this way, it could be available only when the Fixed Time Span option is checked. This would ensure that the underlayer is always viewed at the same timescale as the track being currently edited.

**Describe alternatives you've considered**
Currently I screenshot `m_Jaw+` or whatever phoneme I need to try and sync things up with, or I tab through and place my finger on the screen where something needs to go.

**Additional context**
A potential mockup:
![onionskin](https://user-images.githubusercontent.com/79815367/113070567-c6c9f180-91ba-11eb-8ec9-4ecea40f5c2b.png)

As an aside, it may be beneficial to change the key and tangent colour to something higher contrast than magenta.
White or yellow is excellent for working on dark backgrounds with!

**Comment by henbagle** [comment]
I don't think I have the permissions to assign this issue to myself but I have started working on it 😁
