### ISSUE TITLE
Dialogue Editor - Unable to edit GUI Category

### ISSUE THREAD

**Issue by beccatoria** [ME3Tweaks/LegendaryExplorer#240]
**Describe the bug**
The ability to edit the GUI Control category for dialogue nodes has stopped working in the latest nightly build. A specific package/node is given below, but this seems to be a broad problem.

**To Reproduce**

1. Open BioD_HorCr1_202Warehouse_LOC_INT.pcc (ME2 file) in the Dialogue Editor of the most recent Nightly (see version info below)
2. Select the only conversation in the lower left box (horcr1_shelter_survivor_d_dlg)
3. Go to Node E5. 
4. Right-click and choose Edit Links.
5. The Link Editor will open and the GUI Category column in the centre will be blank. 

Clicking on it once and then again shortly afterwards* will bring up a drop-down menu that seems to allow you to choose a category, but if you do so, then save and close, no change will be actioned and it will be blank again when you reopen it.

*double-clicking will bring up a shortcut to link to the next node. You can cancel out of this and click the blank box again to get the drop-down. This is expected behaviour - I just mention it in case it's not familiar to whomever's looking at the bug.

**Expected behavior**
The GUI Category should be pre-populated. The choices should be able to be changed via the drop down and saving should make them stay. 

Follow the steps to reproduce in the Stable Version and you will see the expected behaviour.

**Version information:**
5.1 Nightly - 4/8/2021
v5 1.0.2642

**Comment by SirCxyrtyx** [comment]
Thanks for the detailed bug report! Will be fixed in the next build.
