### ISSUE TITLE
FaceFX Editor: Cannot Copy Phoneme Tracks Between FXAs in Same Package

### ISSUE THREAD

**Issue by SpaceD0lphin** [ME3Tweaks/LegendaryExplorer#246]
**ISSUE**
When trying to copy a phoneme track from one FXA set to another within the same package, the track will not be copied over.

**To Reproduce**
This problem is present tool-wide and across any PCC, however:

1. Open any LOC_INT file with valid conversations. (For example, `BioD_Nor201Bridge_LOC_INT.pcc`)
2. Locate a node with FaceFX information.
3. Open its FaceFX information in the Editor via the node's Assets tab.
4. Open a different node and its associated FaceFX.
5. Attempt to drag and drop any phoneme track from one open FXA to the other.
6. Observe.

This error occurs regardless of `dlg `conversation file. Whether attempting to copy phonemes in the same `dlg`, or from one to the other, if the target and donor FXAs are in the same `PCC`, the phoneme track will not copy.

**Expected behavior**
The phoneme track should be copied into the target FXA's animation list and should populate at the bottom.

**Screenshots and files used to replicate this**
![image](https://user-images.githubusercontent.com/79815367/116001285-9e7fb800-a5eb-11eb-9095-4ec2d40d4af2.png)

**Version information:**

Tested across Nightly 4-23-2021, 4-24-2021, and 4-25-2021.

**Comment by SirCxyrtyx** [comment]
Fixed by 896d358
