### ISSUE TITLE
FaceFX Editor: Audio Scrub

### ISSUE THREAD

**Issue by SpaceD0lphin** [ME3Tweaks/LegendaryExplorer#248]
**The Issue**
Synchronising what is heard with what is seen is the most time consuming challenge when animating, particularly as most sounds in a word are around 0.1 of a second.
Currently, an external audio program such as Audacity is required, both to to visualise the waveform and offer instant playback. Where an animator is in the line they are animating must be guesstimated and correlated between both programs.

**Describe the solution you'd like**
The ability to hook Soundplorer functionality to within the FaceFX Editor itself would make a monumental difference; the FXA's associated audio could be played at will.
However, the most desirable feature of this audio scrub would be the visual component. As the audio plays, a line passes through the graph. Stopping the audio playback freezes this line in place on the display. This line would be visible at the same point in time across all phoneme tracks.
In this manner, the animator can synchronise what they hear with what they see, and the precision placement of keys becomes much easier. Where to place the key is effectively triangulated.

In wildly idealistic versions of this feature, the audio's waveform would also be visible along with the playback buttons so that periods of silence and approximate length of sounds can also be identified at a glance.
The waveform would not need to be controllable or editable, it would serve as a display only. See mockup:

**Mockup**
The ideal:
![RADFXE](https://user-images.githubusercontent.com/79815367/116796560-43f7c780-aad5-11eb-8c26-cc0053ae573c.png)

**Comment by Mgamerz** [comment]
https://github.com/ME3Tweaks/LegendaryExplorer/commit/e700c63a3c3ca7def22c88d772ae0024ad5fdab6 is part of this

![image](https://user-images.githubusercontent.com/2738836/151036776-742f0d70-93fb-40ae-ab13-6861bf34c020.png)

There is a need for way to draw a vertical/horizontal line(s) in CurveGraph. A good integration might be to make 'fixed time span' automatically be set based on the length of the loaded curve.

**Comment by Mgamerz** [comment]
This should now be fully implemented in nightly. It has audio position data in the graph as well as a waveform which can be enabled on the soundpanel xaml.
