### ISSUE TITLE
Nitpicks on LExplorer

### ISSUE THREAD

**Issue by mirh** [ME3Tweaks/LegendaryExplorer#261]
- [x] I don't even own LE, and yet the first launch had the "Mass Effect LE" game path field pre-filled (with what was just the ME1 path)
- [x] The Azure Pipelines link in the github readme points to the wrong branch (*definitionId=2* rather than *6* I guess)

**Comment by mirh** [comment]
Bingo
https://github.com/ME3Tweaks/LegendaryExplorer/blob/f8752b383b01b22098b780c2472fe57afcd6f69b/LegendaryExplorer/LegendaryExplorerCore/GameFilesystem/LEDirectory.cs#L43-L52

**Comment by henbagle** [comment]
Should have fixed the Steam app ID in 436fb35fc51bbc86057eddacc077943230ca773f

Let me know if this fixes the issue, and I will close the ticket

**Comment by mirh** [comment]
Yup, tested after deleting %appdata%\LegendaryExplorer too.
