### ISSUE TITLE
PMCheckConditional/PMCheckState

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#265]
**Describe the bug**
For some reason it is not recognising modded ME3 PMCheckConditional and PMCheckState exports today. It gives a parsing error, but this appears to disappear once you create a new PMCheckConditional in an LE3 pcc.

**To Reproduce**
Loading Spectre Expansion Mods BioD_Nor_EGM_001_GUI.pcc in Package Editor or Sequence Editor and looking for the sequence SpectreModAuthorisations

**Expected behavior**
Interpreter shows parsing errors

**Screenshots and files used to replicate this**
https://i.imgur.com/ICyuAKB.png?1

https://www.dropbox.com/s/q8bew44t09hju4b/BioD_Nor_EGM_001_GUI.pcc?dl=0

**Version information:**
v6.0.0.3457

**Comment by henbagle** [comment]
Interpreter is trying to look up the bool from a mod plot database, which currently just returns null for OT. This is an issue ultimately for @Kinkojiro as he has been doing some work on it recently, but I have fixed it for the time being by adding a couple extra null checks.
