### ISSUE TITLE
TLK-conversion removes all comments

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#266]
**Describe the bug**
When converting from XML to TLK in the new tools, either LEX or ME3Tweaks the resulting file scrubs out all comments.

**To Reproduce**
Convert any eligible XML to TLK

Steps to reproduce in LEX:
1. Go to 'TLK Editor'
2. Click on 'Import'
3. In folder view select your XML file.
4. In the XML, add a comment like "<--Blablabla-->"
4. Convert the resulting TLK back to XML or view its XML.
5. Any "<---->" formatted comment you added is gone.

Steps to reproduce in M3:
1. Drag and Drop your XML file into M3.
2. Same issue as LEX-example.

**Expected behavior**
Any comment with "<---->" should carry over to TLK format or have an option to scrub it or not.

**Version information:**
LEX version 18-07-2021
M3 version 7.0.3 (Build 121)

**Other information**
I have an extremely long TLK for a big mod, so I need these comments to keep track of where I've written things, because the TLK format increments in ID and iterative changes do not account for the constant increments. If I don't have comments the way I've organized things go out the window and I get lost in my own work.

**Comment by Mgamerz** [comment]
This is not a bug (or even implementable as a feature). TLK doesn't have any way to store comments, and comments are not even read by the XML reader. Comments are for humans, TLK doesn't care at all about that. That's the same with just about all conversion formats that don't have the same system on both sides.
