### ISSUE TITLE
LEX TLK-Manager: "Import" does not work.

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#267]
**Describe the bug**
When selecting "Import" in the TLK-Manager and importing a TLK-formatted XML document nothing happens. 

**To Reproduce**
In LEX open TLK-Manager, and use "Import" on an XML document formatted in TLK-format (for instance, an official DLC TLK converted to XML) and see that it doesn't open properly in the manager. It's empty.

1. Go to 'TLK-Manager' in LEX
2. Click on 'Import'
3. In the Explorer popup select your XML file.
4. The TLK Manager window is still empty.

**Expected behavior**
When importing a TLK-formatted XML document, whether it's directly converted from official basegame/DLC, or custom-edited by the user, the TLK-Manager should open the document and display all its strings as it's supposed to, or as it does when opening directly from a TLK file.

**Version information:**
LEX Nightly 18-07-2021

**Other information**
I'm going by an ME3 (not LE3) TLK. It can open it once it's formatted in TLK by other means but it cannot import the XML. I have not checked if LE3 has the same issue. It could be ME3-specific.

**Comment by Mgamerz** [comment]
Please provide a TLK XML.

**Comment by linkenski** [comment]
[DLC_MOD_YCM_INT.zip](https://github.com/ME3Tweaks/LegendaryExplorer/files/6887876/DLC_MOD_YCM_INT.zip)

**Comment by Mgamerz** [comment]
Looking at the repro steps, did you have a TLK already loaded yet? I can repro your issue but it seems like it's because TLK itself wasn't loaded. (The button should have been greyed out)

**Comment by linkenski** [comment]
I did not have the TLK loaded yet. I was using a previous version, as mentioned in that section. Nothing was greyed out when loading up the window. I see that it is in the current version. Dunno if that’s intentional or not. I thought you were supposed to be able to load up your XML which was edited externally and convert to TLK.

**Comment by Mgamerz** [comment]
A tlk has to be loaded so it knows how to save as there are different types of TLK. They are not defined by the xml.
