### ISSUE TITLE
Cloning or renaming a script should update the "Next item in loading chain" in header

### ISSUE THREAD

**Issue by SterlingVix** [ME3Tweaks/LegendaryExplorer#270]
**Is your feature request related to a problem? Please describe.**
I'm creating a bunch of new Conditionals via a "Multi-clone tree" operation. This produces a bunch of sequentially-numbered functions like:
* `F1994_0`
* `F1994_1`
...etc.

However, the headers for each individual script reference the original function's "Next item in loading chain". In the example above, if the "Next item in loading chain" is `F1993`, it would produce these functions:
* `F1994_0 --> Next item in loading chain = F1993`
* `F1994_1 --> Next item in loading chain = F1993`
...etc.

I renamed this item, so it appears the way I'd expect:
![image](https://user-images.githubusercontent.com/7531113/129300743-d4ca2dc9-8bb7-4328-96e9-5d02b9b923fc.png)

But, by default, all cloned functions will look like this:
![image](https://user-images.githubusercontent.com/7531113/129302023-ca934b9b-1855-485c-bbc8-8d0e34fe2eb7.png)

**Describe the solution you'd like**
I'd like the header to update the "Next item in loading chain" reference to a logical target. Presumably this is:
* for the first clone, the parent
* for subsequent clones, the previous clone.

The header references should also update if the function is renamed. For example, if I have these functions:

```
F2661 --> Next item in loading chain = F2660
F2662 --> Next item in loading chain = F2661
F2663 --> Next item in loading chain = F2662
F2664 --> Next item in loading chain = F2663
```

... and I rename `F2662` to `F3333`, I'd like the headers to update themselves to read:
```
F2661 --> Next item in loading chain = F2660
F3333 --> Next item in loading chain = F2661
F2663 --> Next item in loading chain = F3333
F2664 --> Next item in loading chain = F2663
```

**Describe alternatives you've considered**
At the moment I'm developing an Auto Hotkey script to automate as much of this as possible, but it just emulates a very click-and-highlight-and-copy-paste user workflow.

**Additional context**
I have no idea if this is a "high prio" issue, but I know it'd really help my current project. ;) Thanks as always for your incredible work.

**Comment by henbagle** [comment]
We've already got most of this functionality in the toolset, it's just slightly hidden as it's fairly new and untested. If you select the Class in Package Editor (not any of the functions), you can use an experiment to relink the entire loading chain. The experiment is under `Experiments > Other people's box of Legos > Update Local Functions and Relink`. Experiments must be enabled for you to see the experiments menu. (`Debugging > Enable Experiments`)

**Comment by SterlingVix** [comment]
@henbagle - yes, thank you! I'll check that out today, thanks!

**Comment by SterlingVix** [comment]
@henbagle - it seemed to work just fine, although I can't quite verify it in the game yet. Feel free to close this issue; although I think maybe this feature could be moved out of the `debug` items.

**Comment by SterlingVix** [comment]
I also edited the reference doc I was following, in section 6, to include this experimental feature:

https://github.com/ME3Tweaks/LegendaryExplorer/wiki/Creating-Startup-Files-and-Adding-Custom-Conditionals-for--ME2-Mods

**Comment by henbagle** [comment]
Looks good, but you should definitely have the Class selected and not any of the Functions when you use the experiment. I just had to disable function chain relinking in it this morning, because unlike classes and structs, functions need their chains in a specific order. The script compiler can take care of the function chains most of the time.
