### ISSUE TITLE
Game crashing when a particular function gets recompiled

### ISSUE THREAD

**Issue by lordofstuff** [ME3Tweaks/LegendaryExplorer#271]
**Describe the bug**
When I recompile the function SFXGUI_Store.StockStore in LE3 SFXGame.pcc, even with no changes, everything appears to be fine, but when I run the game, as soon as I open any store (which should call this function), the game crashes. 

**To Reproduce**
Make any change to the above function, such as adding a space, then recompile and save. 
Run the game, and open any store interface (I was using the Bonus Power and Respec stores in the Normandy med bay).
The game will crash. 
This bug happens even if no changes are actually made to the function. The behavior is the same with attempting to use a script update in a merge mod with the same text as the decompilation preview window in LEX. 
I believe the issue is probably not in LEX itself, but in the underlying recompilation tools, apparently not producing valid output in this case. 

**Expected behavior**
When you recompile a function without making any changes, it should behave the same as it did before. It should not crash when running the recompiled function. 

**Version information:**
LEX 6.0 Nightly 8/14/2021, AKA 6.0.0.3534 (latest as of encountering this issue). Also saw it on a previous version, attempted upgrading to latest to see if that would fix it. Have not tested stable. Not a widespread issue, as I have been able to edit many other functions with no issue.

**Comment by SirCxyrtyx** [comment]
Fixed in 32047fa

Latest Nightly fixes the compilation bug. Thanks for reporting this!
> I believe the issue is probably not in LEX itself, but in the underlying recompilation tools

The compiler is part of LEX, not a separate thing.
