### ISSUE TITLE
Changing Sequence Editor toolbox common tab to a favorites tab

### ISSUE THREAD

**Issue by scottina123** [ME3Tweaks/LegendaryExplorer#272]
Would it be possible to to change the common tabs in the toolbox to a favorites tab? I have a sequence objects that I constantly use and having them in one tab would speed up my workflow. Shift clicking to add to favorties would probably work best.

**Comment by henbagle** [comment]
This feature should be implemented as soon as the latest Beta builds. Shift-clicking on a sequence class in the toolbox will add/remove it from your favorites. Favorites are saved per-game.
