### ISSUE TITLE
game crash, details in description of the problem

### ISSUE THREAD

**Issue by carl12345678901** [ME3Tweaks/LegendaryExplorer#283]
whatever i barely modify the healthshield values of a BioH_henchmember_CitSim.pcc from the METR patch01 folder (liara for example) , or a BioH_henchmember_CitSim.pcc from the dlc exp03_base folder (for example edi) the game crash during one of the loading screens that occur at the start of the mission , sometimes during the very first loading , some other times during the loading that occur when you see the little ship that carry shepard and the rest of the squad , the result is that i can't have the modified values for the passive ability for the hench man in the citadel simulator

**Comment by Mgamerz** [comment]
This is not a forum for problems with your mods. This is for reporting issues with the toolset. If you have a problem with the tools, you can follow the template when creating an issue, like all other tickets.

**Comment by carl12345678901** [comment]
go fucking kill yourself you shit head , instead of waste time with such meaningless details just fucking tell me how to solve this problem
