### ISSUE TITLE
another strange thing that cause the game to crash 

### ISSUE THREAD

**Issue by carl12345678901** [ME3Tweaks/LegendaryExplorer#284]
i double checked the following line in the section of gethshieldboost , the one that say:
<Property name="evolve_damagereductionbonus1" type="2">1</Property> , basically in game , in the power's screen that line is displayed as "{unrecognized data_evolve_damagereductionbonus} , but it is absurd since i barely edited the value , didn't edited the line itself

**Comment by Mgamerz** [comment]
This is not a forum for problems with your mods. This is for reporting issues with the toolset. If you have a problem with the tools, you can follow the template when creating an issue, like all other tickets.
