### ISSUE TITLE
Dialogue Ed: Adds broken property upon upon linking

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#288]
**Description**
When making any edit through Dialogue Editor a broken version of a property is copied and pasted onto the BioConversation export. The "m_speakerlist" (from "m_aSpeakerList")

**To Reproduce**
Open any conversation and make an edit, then open the BioConversation through Package Editor, and read the list of properties it has.

Steps to reproduce the behavior, using BioD_ProMar_210Parking_LOC_INT as an example:
1. Open the file in Dialogue Editor
2. Open the BioConversation in Package Editor and check its properties.
3. Try to remove a link between an "entry" and a "player" node.
4. Add the link between them again.
5. Open from Package Editor again and recheck the properties.

**Expected behavior**
See if it has the added property "m_speakerlist" and a list of nonsensical indexes. 

**Screenshots and files used to replicate this**
![image](https://user-images.githubusercontent.com/17158981/136813068-2b203603-34ba-4865-bb5b-e205ccf835c8.png)
![image](https://user-images.githubusercontent.com/17158981/136813074-74eff16d-b789-4f35-ac8a-044b78540558.png)

**Version information:**
LEX 6.0 Nightly dated 11-10-2021

**Other information**
Only noticed this bug for ME3 (not LE3), and haven't checked the others. The m_speakerlist issue is critical enough that it breaks certain conversations (the Earth trial scene messes up) and could be a contributor to some crashes I've had.

**Comment by Mgamerz** [comment]
Looking at this, for some reason in LE1/LE2 (I assume also OT) the speaker lis is 'm_SpeakerList' in bioware files. In ME3 it became m_aSpeakerList and changed from a struct array to a name array.

Our code seems to parse them out properly but does not serialize them back correctly as I don't see any logic changes for games when reserializing the nodes.

**Comment by Mgamerz** [comment]
Oops wrong button.

**Comment by linkenski** [comment]
It's worth noting also that when I tried to clone w/ references, the whole conversation package with that odd property in it, I got an error. After removing it, it cloned with no issue.

**Comment by Mgamerz** [comment]
Yeah it's adding a property type that can't be parsed because it doesn't know the struct array type (see how it shows int? But it was written as struct so it's not 4 bytes each).

I think I have a fix, I'll send you a copy to test before I push it to Beta.

**Comment by Mgamerz** [comment]
This is now fixed in nightly.
