### ISSUE TITLE
Meshexplorer confirmation dialog

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#3]
When certain actions happen in Meshplorer a dialog pops up to confirm the action is complete.   It locks the UI.  However maybe because of lags in mesh changes if the user presses the window again (e.g. accidentally double clicks save) the pop-up comes up behind the main window and freezes the entire UI (across all the programs windows).  It cannot be accessed and requires a taskmanager restart.

The actions include:
save
Import mesh
change material

Suggest: force the dialog always on top.

**Comment by Mgamerz** [comment]
Fixed in 6476913.
