### ISSUE TITLE
Windows Language Settings impair XML-importing in FaceFX Editor

### ISSUE THREAD

**Issue by linkenski** [ME3Tweaks/LegendaryExplorer#318]
**Describe the bug**
When on non-english Windows Language Format Standards the LEX toolset imports values from XML wrong in FaceFX Editor.

**To Reproduce**
In my context, I'm using danish windows settings. You don't need to have danish localization text, but just the system standards, and format. This can be set from [ Control Panel -> Clock & Region -> Change date, clock or number format ] and then under administrative settings tab, "change system locale" from English (US) to Danish.

Now open a LOC INT file in either LE3 or ME3 with Dialogue Editor or FaceFX Editor, because the issue is consistent across either game, from what I know.

**Steps to reproduce the LEX issue:**
1a. If using Dialogue Editor, choose a conversation tree from the left panel at the bottom. Then click a box with dialogue text on it, and go to the "Assets" tab in the right panel, and click on the Theater-Masks icon with the tooltip that says "Open this line in FaceFX Editor".
1b. If opening the file from FaceFX Editor, browse the tab next to the "Load" button, and for example's sake, pick one element with "Player_F", to get a list of FemShep replies for a conversation. Pick another LOC_INT PCC file if there are neither "Player_X" or "Owner_X" listed.
2. Once you've found a conversation to reproduce the issue on, select whichever line you want, and right-click it. Then select "Delete Section of Line". It prompts for Start and End times. Type in "-20" for start, and "20" for end, because no dialogue has animation data for 40+ seconds. This deletes all key data and thus all face animation for that audio cue, so you can import something else into it.
3. Now, right-click that line again, and select "Import tracks from XML". In the explorer popup, choose the XML I embedded in this report.*
4. When in certain system languages the imported XML will get animation data for 45+ hours and values that go way above 1 or 10 which are the usual maximums. If you were on US settings, it imports accurately.

**Expected behavior**
Using the example XML file, which was generated in UDK following SpaceD0lphin's guide, we confirmed that the XML's data is accurate, but my pc would only import properly after changing to US default formats. I confirmed twice that it wasn't just a reboot or other software hangups. The distinction is the system language formats. Ordinarily, the data you will see upon importing, is very similar in length and values to what is seen adjacent to the one you've edited, not several hours and values around 60k.

**Screenshots and files used to replicate this**
![image](https://user-images.githubusercontent.com/17158981/169067868-303fc0e8-877a-4eb7-bcb0-c8e474846999.png)
[XML_to_import_example.zip](https://github.com/ME3Tweaks/LegendaryExplorer/files/8717333/XML_to_import_example.zip)

**Version information:**
Tested with similar results on LEX Nightly 07-05-2022, and 16-05-2022, by me, and also SpaceD0lphin on her computer using the 07-05 build.

**Comment by Mgamerz** [comment]
Is this because the float values use commas instead of dots?

e.g.
I have 3,5 apples
I have 3.5 apples

**Comment by SirCxyrtyx** [comment]
Yeah, it's the decimal separator issue. XML requires the . separator, so parsing floats with the system culture was incorrect. Fixed in 6745d9a7db8c4f3e6aafc66920c77ac39e54fa01
