### ISSUE TITLE
ME2->ME3 Drag and drop header changes

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#39]
The size of the unreal header changed between ME2 and ME3.   When dragging and dropping 4 bytes between 0x28 and 0x2B should be removed.  This applies to both master packages (which have GUIDs and bigger headers) and all objects.

**Comment by Mgamerz** [comment]
Please verify this is fixed in 3.1.2.12.

**Comment by Kinkojiro** [comment]
Fixed
