### ISSUE TITLE
Bug: Interpreter/PathEd/SeqEd not refreshing

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#40]
This is an intermittent bug - I am trying to pin down exactly what causes it, when I do I will update here.

Suddenly, without any particular action I can determine - the interpreter boxes of PackageEd/SeqEd/PathEd stop updating.

If you change a value, it will update but that won't be reflected in the values seen on the screen.  If you click out and back into the object it refreshes to the proper value. This seems to happen across all the main parts of the toolkit.

**Comment by Mgamerz** [comment]
I have seen this in pathfinding editor before. It had something to do with the shared memory implemention, but I couldn't reproduce it reliably.

**Comment by Mgamerz** [comment]
Hard to tell if this is truely fixed but if you can let me know if you've seen this recently I'll keep it open.

**Comment by Kinkojiro** [comment]
No I haven't with .3.1.2.12.  I think it is safe to assume it is fixed.
