### ISSUE TITLE
Null reference exception when extract/replace swf in ME2 pcc file

### ISSUE THREAD

**Issue by Ralf27** [ME3Tweaks/LegendaryExplorer#41]
I got these errors when clicking on extract or replace swf in ME2 pcc file.

![error replace swf data](https://user-images.githubusercontent.com/39481912/40350931-742bf554-5dab-11e8-842a-88d5c8eeb6a4.jpg)
![error extract swf data](https://user-images.githubusercontent.com/39481912/40350932-74549374-5dab-11e8-90b3-ba6f1da90e2b.jpg)

**Comment by Mgamerz** [comment]
Can you tell me which file and export (#) you are running this on? This seems to indicate that the RawData/Data value did not exist, which for SWF exports should always exist.

```
var props = swfExport.GetProperties();
string dataPropName = pcc.Game != MEGame.ME1 ? "RawData" : "Data";
ArrayProperty<ByteProperty> rawData = props.GetProp<ArrayProperty<ByteProperty>>(dataPropName); //this value is null
```
