### ISSUE TITLE
PackageEditorWPF/InterpreterWPF: Right click context menu items

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#43]
For InterpreterWPF (in PackageEditorWPF), it is now backed by PropertyCollection instead of a spaghetti monster of parsing. Using this we can use the features provided by PropertyCollection to easily enumerate data, for features like array sorting.

**Comment by Mgamerz** [comment]
This is going to be worked on soon, once tree view drag and drop is implemented... ugh... tree view wpf drag and drop...

**Comment by Kinkojiro** [comment]
Works!

**Comment by Mgamerz** [comment]
Just wanted to follow up and make sure this works as you expected. I made a few changes to it since in the code that powers it.

**Comment by Kinkojiro** [comment]
Sorting is great thank you.  Validated.
