### ISSUE TITLE
Editing in curve editor results in massive increases in object size, via replication of "none"

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#47]
When editing InterpTrackFloatMaterialParam or InterpTrackFloatParam in curve editor the object size increases due to additional unreal properties being added.

None appears to be replicated again and again.  sample file on discord.
Obj #3292
and Obj# 3306
are examples

**Comment by Mgamerz** [comment]
I will need instructions to reproduce this. I edited a InterpTrackFloatParam and it didn't have an issue.

**Comment by Kinkojiro** [comment]
more details:

Open the sample file.  Go to Obj 2750 (InterpTrackFloatProp)

Open in curve editor, adjust.  
Now press save in curve editor.

The FloatTrack creates a large number of new "Nones"

you can see the change in the package ed hex.  (it also shifts down TitleTrack and any other subsequent properties

**Comment by Mgamerz** [comment]
![curveed](https://user-images.githubusercontent.com/2738836/45005737-55017b00-afb2-11e8-8648-b05b840b4de5.gif)

I have changed how curve editor works in my current codeset, and the next release will be removing the "Save" option in curve editor. I will get you an updated build once I do some more testing.

Curve editor works by updating the export in real time as you move a point. You can see how this behaves in the above gif.

This is still present in my build, however the save button in your build saves the pcc, which seems misleading as it's a separate window, and would lead to you thinking you're commiting the curve export, but it's really commiting the pcc.

The curve editor has been altered to be embeddable, and is also now in Package Editor WPF. I have also changed how saved exports are done that should hopefully block this from occuring, as curve editor would mark exports as changed simply by viewing a curve, even if nothing was modified.

**Comment by Mgamerz** [comment]
I have posted a new build for you to test on my discord server.

**Comment by Mgamerz** [comment]
New build posted that should fix this issue

**Comment by Kinkojiro** [comment]
Now fixed thks

**Comment by Mgamerz** [comment]
Fixed by https://github.com/Mgamerz/ME3Explorer/commit/1d342c244c21a73c160d8e55654570e59e2df6c5
