### ISSUE TITLE
Adding properties for some classes does not work

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#49]
It appears at some point the property lookup system broke down and some classes are not resolving their properties (like staticmesh in ME3). 

Cause unknown for now.

**Comment by Kinkojiro** [comment]
**IN PACKED_WPF** 
_ME1:_
SkeletonMesh does not parse  but you can add properties (which causes an exception)
StaticMesh parses but adding properties results in "no properties available"

_ME2:_
SkeletonMesh does not parse but you can add properties (which causes an exception)
StaticMesh parses but adding properties results in "no properties available"

_ME3:_
SkeletonMesh parses and you can add properties
StaticMesh parses but adding properties results in "no properties available"

**Comment by Mgamerz** [comment]
StaticMesh is a native class in UE3, as such we do not have a list of properties that we can add to it. I am fairly certain this is the same as it was in classic, as the adding dialog is the same for classic and wpf, and I have not changed the object info file for ME3.

**Comment by Kinkojiro** [comment]
You are correct but I don't understand why staticmesh is any different from any other "native" class that is defined in Engine.pcc.

These are the list of properties that  are used in the staticmesh in ME3

![image](https://user-images.githubusercontent.com/15979398/51631848-b61bf200-1f45-11e9-86e8-033e26ff1286.png)

**Comment by Mgamerz** [comment]
StaticMesh is not defined in Engine.pcc. As a native class it is defined in the game executable.

**Comment by Kinkojiro** [comment]
Ok.  It is not really a big deal as it parses.

**Comment by Mgamerz** [comment]
I have extended how information is generated, allowing us to add custom entries. We may be able to add stuff for native classes using this method. Using this we can reliably rebuild the information, and if we add your new custom items, we can include those too.

**Comment by Kinkojiro** [comment]
Nice great idea.   When you get this release out the way maybe you can point me to the code and I will try to add these native classes where possible.

**Comment by Mgamerz** [comment]
Parsing has been implemented for all 3 games, should be 100% coverage now.

I am closing this issue for now as it is tagged for 3.1.12.14. Please open a new issue for 4.0/3.1.12.15 (may be a bugfix release) for adding properties to staticmesh, I have added the code for your custom classes to ME3UnrealObjectInfo generating, adding staticmesh would be done in the same way.
