### ISSUE TITLE
Meshplorer failing to preview meshes

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#50]
Upon previewing a mesh for the first time, Meshplorer gives a SystemOutOfMemory error. Subsequent times result in properties/hex loading but the visual preview missing.

Attempting to view a mesh for the first time:

![capture](https://user-images.githubusercontent.com/39216095/46054863-6c62fc80-c149-11e8-897a-94bea18c3da9.PNG)

Further attempts:

![capture2](https://user-images.githubusercontent.com/39216095/46054926-c4016800-c149-11e8-82be-62f23abbfd5b.PNG)

Occurs in any package, regardless of DLC or mod.

I'm using ME3 Explorer version 3.1.2.13, digitally signed on September 9th, 2018.

Switching to as late as 3.12.12 results in Meshplorer working as intended.

**Comment by Mgamerz** [comment]
Please attach sample files and instructions on how to reproduce this issue.

**Comment by ghost** [comment]
https://www.dropbox.com/s/0t7m2xccmgwmb4i/BioA_End001_450AlienHall.pcc?dl=1

Don't know if it'll work without my TFC or BioP, but if it doesn't, literally open any package in the game and try to view a mesh.

**Comment by Mgamerz** [comment]
You're going to have to be specific about what the issue you're actually having is. Acting strange does not really mean anything to me, as I don't use meshplorer very often. I have opened this file, and did not have any issues viewing several meshes.
