### ISSUE TITLE
Bug when importing a mesh

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#51]
Sorry for posting again, I'm only reporting bugs and errors that I see in 3.1.2.13 and not in 3.1.2.12.

I think this might be a problem with this particular mesh, and not related to my PC specs this time.

This is the binary of the Mesh from the origin package. The mesh is HMM_ARM_CTHb_MDL (export 7503).

![mesh import error](https://user-images.githubusercontent.com/39216095/46085425-50417880-c1a6-11e8-963b-af9f5c968f41.PNG)

However, after importing this to another package, in my case BioD_End001_460_RoofInterior (_I have tested it by importing to other packages too, and the same thing happens_), this happens to the binary:

![mesh import error 2](https://user-images.githubusercontent.com/39216095/46085639-bcbc7780-c1a6-11e8-985c-09d03cf83cf8.PNG)

The single binary slot for the material gets replaced by 7 slots which are intended for SkeletalMeshSockets. This obviously breaks the mesh.

![error 3](https://user-images.githubusercontent.com/39216095/46085890-56842480-c1a7-11e8-9d38-224def79b30f.PNG)

As before, this does not occur with 3.1.2.12, only with .13.

Oddly enough, this happens only with this specific mesh.

If this is due to my PC specs again, I apologize. I do not know what changes were made (outside of Meshplorer) that demand more PC power.

Origin Package with the mesh: 

[BioD_Nor_001Global.zip](https://github.com/Mgamerz/ME3Explorer/files/2420113/BioD_Nor_001Global.zip)

I have also tried to import this mesh from other Normandy packages. Same result.

**Comment by Mgamerz** [comment]
When a skeletal mesh is ported between files, there was already some existing code for tweaking it as it was copied - this may be due to that. This was not written by me so I'll have to investigate what the code is doing.

**Comment by Mgamerz** [comment]
This appears to be fixed in my September 27th build.

**Comment by Mgamerz** [comment]
Please check this in the final 3.1.2.13 build I just posted.
