### ISSUE TITLE
Move Metadata editor to ExportLoaderControl (with support for Import loading)

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#59]
All tabs in PackageEditorWPF are currently ExportLoaderControls. They can only handle exports. Metadata tab is different as it can load both imports and exports for editing.

To simplify the code for PackageEditorWPF, we should move Metadata editor to it's own loader control. We would make a EntryLoaderControl parent which ImportLoaderControl and ExportLoaderControl would inherit from. I know ImportLoaderControl would not see much use since you can really only edit metadata, but it would help simplify the tool and standardize how the tabs are handled.

**Comment by Mgamerz** [comment]
This should be implemented. It just needs checked for bugs when using it. I have fixed all the ones I have found.

**Comment by Kinkojiro** [comment]
Validated.  Thank you.
