### ISSUE TITLE
BinaryInterpreterWPF Generic Scan: Add byte shifting

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#62]
In many other modding tools that contain binary data (like GBA bitmaps) the data is often not byte aligned to the beginning. It will be beneficial to add byte alignment options from the binary start offset when doing generic scans so users can see possible patterns.

**Comment by Mgamerz** [comment]
This should be implemented, it needs a bit of testing however.

**Comment by Kinkojiro** [comment]
Please put MaterialInstanceConstants as analysed as generic.  They often start like a material with a set of texture references but then have names and a second set of texture references.
