### ISSUE TITLE
TLKManager for package editor

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#65]
Add ability for package editor to use DLC & Mod tlks to display strings, language selector, checkboxes, that kind of stuff. With settings that save too.

**Comment by Kinkojiro** [comment]
works.

**Comment by Mgamerz** [comment]
I would say this is implemented. Perhaps not perfectly, but the original feature request has been fulfilled, we can open a new issue to implement changes to the UI.
