### ISSUE TITLE
Metadata Editor WPF: Dropdowns searchable/keypress search

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#66]
Currently the MetadataEditorWPF control does not work with keypress search on the comboboxes. In Package Editor classic, you could search for an item by typing it in - due to how I set up the comboboxes for this control it is not possible as searches are done from the first character and the entire item is a string.

We may need to make a class containing the index and the item it is referencing. This way we can prefix a displayable value but search on the parsed entry value.

**Comment by Mgamerz** [comment]
For this to match old package editor format, this will require the packageeditorwpf indexed name list datatemplate for the dropdowns. Will implement soon.

**Comment by Kinkojiro** [comment]
This works for the Name, but not for the dropdowns class, superclass, link or archetype.
