### ISSUE TITLE
Analyze ShaderCache

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#71]
ShaderCaches have long been an annoying export type for all 3 ME games (especially ME3). It seems they have some sort of pointer references that will bust if we recompact the file.

They contain embedded compiled Direct3D shader model 3 files, along with headers that seem to in a list of length 0xB as well as what appears to be a footer. We're a long ways out from understanding these, but assuming we can bust the file up into chunks we may be able to perform the following:

 - Fix ME1 black blobs due to missing 3DNow! instruction set on ME1. I am pretty sure the shadercache contains instructions for this on the CPU, however it is embedded in a huge 70MB shadercache
 - More easily modify ME3 DLC files

Each game was compiled using a specific version of the Direct3D shader compiler - this version can be detected by looking at the header of the compiled HLSL files in the shader cache.

**Comment by Mgamerz** [comment]
I am going to guess this has been completed for ME3. I'm going to close this for now but we should ensure the shader cache can be read for ME1 and ME2 - with ME2 receiving the reconstruction implementation as well.

**Comment by mirh** [comment]
So.. I see you are already somewhat able to open `RefShaderCache-PC-D3D-SM3.upk`s. 
(even though I couldn't do anything more than "just read such shader name exists inside", idk if it's just me, or this is what you always meant with "we can't decompile shaders")

But what about `GlobalShaderCache-PC-D3D-SM3.bin` in ME3?

While trying to figure out the code for the "Filmic Response" effect on the ME2 360 release, I ended up hitting the roadblock that unlike the corresponding pc release (that has everything in `Engine\Shaders`) all shaders are packed in [GlobalShaders-Xbox360.bin](https://github.com/ME3Tweaks/ME3Explorer/files/6045042/GlobalShaders-Xbox360.zip). 

And after some jiggling around the net I found a) once accounted for endianness it is the same format that will then be used in ME3
b) it's actually *somewhat* already half-way documented (0x47534D42, meaning GSMB, aka Global Shader Map Binary)
https://github.com/blackix/blackix/blob/4.0/Engine/Source/Runtime/Engine/Private/GlobalShader.cpp
https://github.com/DarkStarSword/3d-fixes/blob/master/extract_unreal_shaders.py

I'm not an RE expert, but maybe the fact that it's a small file, with some clue already available, including that some of the plaintext is already known, may help.

**Comment by Mgamerz** [comment]
It does look a prebuilt version of the LocalShaderCache that was used in ME1 (and ME2, but I don't think it serialized to disk, just into memory on boot). 

It might be somewhat useful, though I did not work too much on Shader Caches, that was mostly @SirCxyrtyx.
