### ISSUE TITLE
DLC Unpacker: Icon needed

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#83]
DLC Unpacker doesn't have an icon. We'll need one before 3.1.2.14 ships.

@Kinkojiro you made one for pathfinding editor a while ago - think you could make:
DLC
Unpacker

?

**Comment by Kinkojiro** [comment]
Okay.  I will do my best

**Comment by Mgamerz** [comment]
As we are approaching the end of the issues for 3.1.12.14 I will need this icon soon.
