### ISSUE TITLE
Analyze StaticMeshCollectionActor

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#84]
Some of the binary properties for StaticMeshCollectionActor were found by me. Once I found what I needed I never bothered with the other data. It would be nice if we could determine the rest of the binary data format.

![image](https://user-images.githubusercontent.com/2738836/47752746-f297c480-dc5a-11e8-8136-3999145c0ae7.png)

**Comment by Kinkojiro** [comment]
0?, 1, 4, 8 look like quaternion.  I am not sure what the points in between are, maybe scalars.   The point about SMACs is they are optimised locationally for fast computation, unreal, like most 3d engines, will use quaternions to calculate scale and rotation.  This way they are pre-calculated.

[https://en.wikipedia.org/wiki/Quaternion](url)

In the wikipedia nomenclature I imagine: 0= a = -1, 1 = i, 4 = j, 8 = k

**Comment by SirCxyrtyx** [comment]
It's a [4x4 position matrix](http://www.euclideanspace.com/maths/geometry/affine/matrix4x4/index.htm).

**Comment by Kinkojiro** [comment]
I believe this can be closed?
