### ISSUE TITLE
Minor: Name list: Add copy option and edit actually opens with the name

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#85]
**Is your feature request related to a problem? Please describe.**
Missing some basic functionality to speed up editing names list.

**Describe the solution you'd like**
Add copy option to right click on name context menu.
When clicking edit the name actually appears in the box (already fully selected)
When adding a name, refresh the name list (or better still global refresh)

**Comment by Mgamerz** [comment]
When adding a name the namelists should be automatically updated across the tool. Other tools should update accordingly through handleUpdate().

I am not sure what you mean with copy name. Is this so you can make new names that are super long (like wav names)? Or are we talking about copy name as string?

**Comment by Kinkojiro** [comment]
Validated.  Copy, edit and global refresh works.

Thank you
