### ISSUE TITLE
Bug Minor: PackageEd - Import and Replace binary impacts wrong object + other minor issues

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#89]
**Describe the bug**
 2 When transferring sequence objects between files the variable links are not set properly (expected type)
 4 when adjusting an import link via metadata, changing the link object actually changes the index of the package name.

**To Reproduce**
Try to export and replace any object in packageed WPF
 4 change the link of any import in pacakageed WPF

**Comment by Mgamerz** [comment]
Can you get me some sample files and indexes for point # 2. Point # 1 fixed. I don't think I had implemented Point 3 before we took a break. Will look at it.

**Comment by Kinkojiro** [comment]
point # 2 copy obj 169 seqact_teleport from BioD_Kro001 to any other pcc.  The variable links expected type seqvar_objects will not be correct.

**Comment by Mgamerz** [comment]
Yes I can see this. It appears this is not being relinked even though relinker is not reporting any failures.
![image](https://user-images.githubusercontent.com/2738836/48956613-36f04a80-ef11-11e8-8f79-57de9c3fad99.png)

Likely this means I missed some sort of edge case, like struct array children or something.

**Comment by Mgamerz** [comment]
2 should be fixed now. I was not adding a singular dropped item to the list of cross mappings, so it wasn't relinking. Now it relinks.

**Comment by Kinkojiro** [comment]
2 validated - fixed.
4 validated - relinking works.

Much appreciated
