### ISSUE TITLE
Bug: Changing link does not update tree view

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#90]
Changing the link does not move the node in treeview, forcing you to reload the tree to see it

**Comment by Kinkojiro** [comment]
This is true of a number of different scenarios; also changing the name (editing the name table), and some other metadata.

**Comment by Mgamerz** [comment]
This has been implemented, but is not yet being closed because other areas need to be refreshed.

**Comment by Mgamerz** [comment]
This issue is being closed, please see #54 for tracking this as it is also mentioned there. As of time of this comment, there should be improvements to refreshing lists
