### ISSUE TITLE
Minor Bug: FaceFX Editor doesnt fix zero entry animsets

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#91]
**Describe the bug**
The FaceFX editor, when opening a blank (zero line) facefxanimset, does not adjust the node table so it works with adding a line.

This can be fixed by fixing the node table (by hand). Ideally this should be checked whenever a new line is created or copied into a FaceFxAnimSet.

You can see the contents of the Node Table using the FaceFxAnimSetEditor:

Blank Animset Node Table:
![image](https://user-images.githubusercontent.com/15979398/49353753-c01e3300-f702-11e8-8f51-686649e48370.png)

Correct Animset Node Table:
![image](https://user-images.githubusercontent.com/15979398/49353772-de842e80-f702-11e8-94a8-0b4363e2647b.png)

**To Reproduce**
1. Open BioD_Cat002_Bridge_LOC_INT.pcc with FaceFX Editor
2. Copy a line to the FXA_cat002_bridge_crossing_b_Owner_F
3. Save and open in FaceFXAnimSet Editor

**Expected behavior**
Adding a line to FaceFXAnimSet sets the table to identical as above.

**Comment by Mgamerz** [comment]
@SirCxyrtyx This is your domain right? Any chance you could look at this so we can include it in 3.1.12.14?
