### ISSUE TITLE
Feature Request: Search by Tag

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/LegendaryExplorer#96]
Often times there's a need to find an export with a specific tag, however, this can be a big time-sink in large files.

The option to search by tag would be very useful for Object_Tag_By_Find's or when trying to find referenced objects that are in other files.

**Comment by Kinkojiro** [comment]
Confirmed this works.  Thank you

One thing with name table dropdowns.  It is really difficult to use for files that are extensively edited (like Ark or Omegahub).  The Name list is no longer in order, so a box that you write the name and it shows likely candidates is much more useful than a dropdown.

**Comment by Mgamerz** [comment]
Could consider (not in this release) a way to have alphabetized names in the UI, which would search alphabetically instead. Right now name dropdowns are done through a class I made called IndexedName. However that would be a different feature request, for now I will close this.

**Comment by Kinkojiro** [comment]
For future ref this box in binary interpreter is ideal:

![image](https://user-images.githubusercontent.com/15979398/51634306-d9e23680-1f4b-11e9-9d96-e811d619a5f3.png)
