### ISSUE TITLE
Feature: Kismet graph positioning data in the cloud

### ISSUE THREAD

**Issue by Mgamerz** [ME3Tweaks/LegendaryExplorer#98]
As a feature for ME3Explorer ME3Tweaks 4.0, I am planning (haven't done any work yet) on a database system that will allow developers to share their kismet graphs for ME2 and ME3. 

## Why
ME2 and ME3 kismet graphs do not include positioning information for nodes in the graph. They appear to have been stripped as part of the optimization phase of compiling. As such, some of the more complicated graphs are notoriously difficult to sort out.

## Who benefits
Developers who modify kismet graphs into more-human readable work spend can significant time doing so. Since many files in the scene are looked over by many others, there is a great deal of duplicate work. Determining the flow of a kismet graph can be a very tedious task.

A cloud based system that can gather multiple developers' work on sorting graphs could significantly improve the modding experience for other developers when they are modifying the same kismet sequences.

This system would be focused on vanilla files, as all files are based off bioware vanilla files. Further investigation will help determine if this could apply to modded files, renamed files, and other details.

## How
This system would be powered by ME3Tweaks, with the upload authentication method through ME3Tweaks ModMaker. ME3Explorer already contains the ability to store graph position information, in local json files called Sequence Views. These are the files that would be used. They would require a slight extension to incorporate information such as author, modification date, and a bit more metadata about the file.

Users uploading data would be entirely optional. Graphs could be vetted by experienced developers. Data would not directly flow into into production, it would first go to staging.

## User flow
When a file/sequence that matches a server version exists is opened in Sequence Editor, an option to download the positioning data would be presented to the user. This would be done either by querying an ME3Tweaks API endpoint, or by looking at a local positioning file manifest. Depending on the size of the database, the entire database of positioning may be downloaded and cached, however this presents issues with versioning.

The file would be downloaded and cached. Ideally I would also like to provide a way for users to download the cache, or ship a cache with ME3Explorer directly so in the event of ME3Tweaks disappearing the data is not lost.

## Challenges
Some challenges are presented by this feature request.
 - Seasoned developers will have to vet the first files
 - Submitting a file would likely include submitting an image. We may need to find a more efficient way to take screenshots of kismet graphs as taking screenshots as bitmaps simply uses too much memory when graphs can be huge. While the final image can be anything, the process of generating the bitmap object requires a huge amount of memory. We may need to find ways to segment it up.
 - Extending the sequence view system will take some time
 - Local sequence views would have to be accounted for
 - Extensions to the ME3Tweaks authentication system will be required to allow for multiple roles of a user

**Comment by Mgamerz** [comment]
I'm thinking @SirCxyrtyx 's auto layout has killed the need for this.

**Comment by SirCxyrtyx** [comment]
Considering the significant time investment that would be required to implement this, it would have to provide a lot of value to be worth it. With auto layout providing a good untangling for most sequences, and a usable one for the rest, I don't think this is worth pursuing.
