### ISSUE TITLE
Bug: Binary Interpreter for Materials incorrectly looks at GUID counts as consecutive

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Tweaks/LegendaryExplorer#99]
**Describe the bug**
In package editor (WPF) the binary interpreter looks at materials and assigns the first number as GUID count. This may or may not be correct, but what is definitely wrong is to assume that means there is 1 a GUID followed immediately by another GUID.  Instead the GUID has a bunch of texture references and then another GUID.

For example:
![image](https://user-images.githubusercontent.com/15979398/51740686-9cd18d80-208c-11e9-89a6-860fc6c03e30.png)

**To Reproduce**
Open BioD_Kro002_400highway.pcc
Go to Object 1677 for an example of a material where the GUID count incorrectly parses the file (most of these effectsmaterials are identical.

**Expected behavior**
GUID count should not be used to parse the binary.

**Comment by Mgamerz** [comment]
I can see this. If the GUID is followed by an int 1, it seems to have texture data following with Count(4) and then the list of texture object refs. 

However there is other data trailing this list before the next GUID. Unless we can determine the file structure after the texture lists that, we don't have a way to parse it.

This class may be like Bio2DA, where reading the binary requires reading the properties.

**Comment by Kinkojiro** [comment]
We probably don't have a way to parse it.  There isn't a lot we can do about that without knowing how shaders work better.   In any case what we do know is that using GUID count in the parsing pretty much always creates a problem if you are trying to fix textures in a material.   Previous versions of the parser ignored it and worked better.
